### ISSUE TITLE
Cpu占用和电量消耗有点大

### ISSUE THREAD

**Issue by lrc0000** [ddddxxx/LyricsX#102]
cpu占用和电量消耗都在20左右，几乎是iTunes的两倍了，是我的电脑原因吗？

**Comment by ddddxxx** [comment]
已确认。通过 AppleScript 获取当前播放音乐信息时，会出现如下错误：

```
AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
```

这似乎是 macOS 10.13 的一个 bug。即使在 Script Editor 中运行脚本也会出现错误。

```applescript
tell application "iTunes" to get current track
```

由于获取播放信息是必要的，目前似乎没有办法解决。只能等待 Apple 修复这一问题。

**Comment by ddddxxx** [comment]
可以优化程序架构以减少查询频率。需要大幅重构。进行中……

**Comment by msongz** [comment]
同耗电
平均93
是从mbp 2016 开始出现电量去到10以下发现的
