### ISSUE TITLE
TodayWidget 底部圆角有锯齿

### ISSUE THREAD

**Issue by Arrow-Li** [ddddxxx/LyricsX#103]
![fullsizerender](https://user-images.githubusercontent.com/17962902/31676955-d0e23dd6-b39b-11e7-89c9-129274e2e857.jpg)

**Comment by ddddxxx** [comment]
这个锯齿是固有的，只是在浅色 widget 中不明显。你可以在所有深色 widget 上观察到这个问题。
这应该是系统的一个 bug，程序无法改变。
