### ISSUE TITLE
外接显示器问题

### ISSUE THREAD

**Issue by kuyu132** [ddddxxx/LyricsX#105]
当macbook外接显示器的时候，两个显示器的排列方式是外接在上，笔记本的在下，因为外接显示器是主力，但歌词总是跑到外接显示器上，而且无法移下来，另外希望在全屏的界面希望不要显示歌词。

**Comment by kuyu132** [comment]
可以参考下网易云音乐的歌词显示

**Comment by ddddxxx** [comment]
感谢建议。有关外接显示器的想法请在 #57 中讨论。由于缺少设备，目前无法进行相关开发，仅作收集建议之用。

LyricsX 的逐行歌词是一个不可交互的浮层，而非网易的常规窗口。我认为在全屏应用界面显示歌词是更符合逻辑的做法。
