### ISSUE TITLE
歌词匹配问题

### ISSUE THREAD

**Issue by Johngithubb** [ddddxxx/LyricsX#106]
#请把我删掉吧，我又看过一遍设置，发现“歌词文件保存地点“下有一个‘加载同名歌词’的选项，原先以为是加载文件夹中的已有同名歌词，现在想想应该是我的问题的造因。抱歉。#

发现歌词匹配时，似乎忽略了歌手的信息。有大量歌名相同，歌手不同，也确实不是同一首歌的情况，但是由于忽略了同时匹配歌手信息，导致歌词张冠李戴。另外，如果确实存在没有歌词，但有同名歌曲的歌词，也希望不要匹配显示出来（或者有个是否显示的选项给用户）。由于我是默认写入iTunes的（毕竟准确的情况多），所以这时候还要报错，有些麻烦。
感谢作者开发。
PS：又过了几遍不同的歌，软件似乎的确是同时匹配歌曲名和歌手的，但是我不知道为什么有些歌会忽略正确的匹配而去匹配其他歌手的歌词。

**Comment by ddddxxx** [comment]
“加载同名歌词”的意思是“加载与音乐文件在同一文件夹且名字相同的歌词文件”，详见 #66 

关于不显示“张冠李戴”的歌词，有许多歌词的信息并不完全准确，例如大小写、格式、括号等，程序难以判断，目前只能全部显示，由用户挑选。
