### ISSUE TITLE
Configurable lyrics window

### ISSUE THREAD

**Issue by yay** [ddddxxx/LyricsX#107]
Currently the window looks like this (not to scale):

![screen shot 2017-10-26 at 01 37 54](https://user-images.githubusercontent.com/1799756/32028334-67185c9c-b9ee-11e7-88da-08b7a0db63b3.png)

It looks neat and stylish, but the font is a bit too small and the contrast too big for my liking. Hurts my eyes.

Would it be possible to make the font color, highlighted font color, background color and font size configurable?

**Comment by ddddxxx** [comment]
Of course, since karaoke lyrics is configurable, there is no reason not to do this.

Currently I’m refactoring the codebase of this app. your request will probably not be implemented very soon.

**Comment by Alcivar** [comment]
The Lyrics Window is currently the only option for viewing the entire lyric. You should be able to control the look of it.
