### ISSUE TITLE
可否增加对audirvana plus的支持

### ISSUE THREAD

**Issue by jerryzmtz** [ddddxxx/LyricsX#109]
官网https://audirvana.com/

**Comment by ddddxxx** [comment]
Audirvana 有可用的 Apple Script 接口，理论上可以支持。

由于 Audirvana 用户较少，这一功能优先级非常低。如果你也有这一需求，请在下方留言，我会视情况调整优先级。

有能力者可以尝试自行开发，参见[这里](https://github.com/ddddxxx/LyricsX/blob/master/LyricsX/MediaPlayer/MusicPlayerProtocol.swift#L40)。

**Comment by ddddxxx** [comment]
感谢 @tzhao11 实现了对 Audirvana Plus 的支持。

这是一个给 Audirvana Plus 用户的临时版本，由于系统重构，主版本将会稍晚支持。

[LyricsX.app.zip](https://github.com/ddddxxx/LyricsX/files/1465946/LyricsX.app.zip)

**Comment by seagle0128** [comment]
有开发的手册吗？如果架构合理可以自行扩展支持很多播放器，比如Audirvana、pineplayer等等。

**Comment by ddddxxx** [comment]
@seagle0128 所有播放器相关功能均在 [ddddxxx/MusicPlayer](https://github.com/ddddxxx/MusicPlayer) ，由我个人维护，目前没有文档。如果你愿意协助开发，可以直接和我交流。

目前该模组已支持 Audirvana ，只剩下主程序 UI 方面的改动，应该很快能完成。

**Comment by 476678244** [comment]
你好！
实测Audirvana 3.5.18 还不能被识别。
希望修复一下！感谢！

**Comment by ddddxxx** [comment]
@476678244 请问使用的哪个版本？1.5.2测试版有一些问题，请退回到1.5.1正式版。
