### ISSUE TITLE
Shortcut to show/hide

### ISSUE THREAD

**Issue by felipe-lookmysite** [ddddxxx/LyricsX#117]
I used to use GimmeSomeTune on iTunes and now find the LyricsX to use with vox which seems a lot better, but I guess a feature can help a lot it's a shortcut to Show and Hide the lyrics window.

**Comment by ddddxxx** [comment]
There are 3 different mode to display lyrics, do they all need shortcut?

**Comment by felipebertolini** [comment]
I guess only Lyric window and Karaoke. and maybe added the title and name of the artist as title on Lyric window (this helps a lot when you are on shuffle).

![image](https://user-images.githubusercontent.com/13525019/33023248-cb9e087e-ce07-11e7-9550-2489d705b5fa.png)

**Comment by ddddxxx** [comment]
I'll implement this shortcut soon. Title and artist display will be added later with playback control (#113).

**Comment by mikedvzo** [comment]
Love the program and will definitely donate if you add this shortcut feature to "Show Lyric Window"

**Comment by ddddxxx** [comment]
[enjoy!](https://github.com/ddddxxx/LyricsX/releases/tag/v1.4.0)

**Comment by felipe-look** [comment]
It's perfect! and if it's not asking too much, could you make a show / hide function?
