### ISSUE TITLE
很奇怪，为什么几乎每次歌词都显示不对呢？

### ISSUE THREAD

**Issue by HOTOOO** [ddddxxx/LyricsX#118]
几乎每次都是。
每次都得重新搜索，再重新选择正确的歌词。
关键是搜索列表里面有正确的歌词啊，而且歌名和歌手都匹配上了。
是什么原因呢？求教。
谢谢。

**Comment by ddddxxx** [comment]
mac 版和 iOS 版共用歌词模块，出于流量消耗考虑，自动搜索时，每个歌词源仅加载第一个结果。

会在近期修复。

**Comment by ddddxxx** [comment]
已确认是另一个问题，导致歌手名没有参与搜索。下个版本修复

**Comment by HOTOOO** [comment]
谢谢。
