### ISSUE TITLE
Show lyrics on 2nd display ?

### ISSUE THREAD

**Issue by jden4321** [ddddxxx/LyricsX#119]
Hello.  Lyrics is excellent -- thank you for writing it!  Would it be possible to change a setting so that the karaoke and lyrics windows could be displayed on a second (extended) screen, so that iTunes could be on the primary screen and karaoke on the second screen?  This would be super helpful.  Thank you!

**Comment by ddddxxx** [comment]
Hi, I am willing to add this feature. However, I do not have extra display. I not only do not know how it looks like, nor can I debug it.

You can pay attention to #57. I will keep updating there.
