### ISSUE TITLE
Version 1.2.2 doesn't even open on macOS High Sierra (10.13.3)

### ISSUE THREAD

**Issue by ranuraag** [ddddxxx/LyricsX#123]
Version 1.2.1  worked for me. Ever since the update, the app doesn't even open.

**Comment by ranuraag** [comment]
can you provide a download link for version 1.2.1 until a fix can be worked out?

**Comment by ddddxxx** [comment]
You can download from [GitHub releases](https://github.com/ddddxxx/LyricsX/releases/tag/v1.2.1).

**Comment by ranuraag** [comment]
tried v1.2.3 today it fails to launch. Rolling back to v1.2.1 until fix is released.

**Comment by ranuraag** [comment]
figured out the issue, installing the latest version of xcode solved the issue. This thread can be closed.

**Comment by ddddxxx** [comment]
@ranuraag Thank you, It helps a lot.

It seems the app attempt to load dynamic library from Xcode, which already embed in app's bundle. I'm still working on this. Anyway, LyricsX should not rely on Xcode.
