### ISSUE TITLE
封面功能加入

### ISSUE THREAD

**Issue by KoukiSadamoto** [ddddxxx/LyricsX#124]
请问能否在歌词搜索框右侧加入自动搜寻歌曲封面的功能。当前封面均显示为iTunes默认封面。谢谢。
<img width="472" alt="2017-12-09 15 37 36" src="https://user-images.githubusercontent.com/33309533/33793207-ecd4de2a-dcf6-11e7-96c4-ce19dfcf229c.png">

**Comment by ddddxxx** [comment]
@KoukiSadamoto 某些歌词带有封面，选择后会显示在右侧。至于专用的封面搜索功能，目前并不打算加入

**Comment by ddddxxx** [comment]
close due to inactivity
