### ISSUE TITLE
能支持 Audirvana Plus 吗？

### ISSUE THREAD

**Issue by seagle0128** [ddddxxx/LyricsX#128]
目前支持的播放器有点少，能支持 Audirvana Plus 吗？

**Comment by ddddxxx** [comment]
见 https://github.com/ddddxxx/LyricsX/issues/109#issuecomment-343837065

这是一个基于较旧版本的修改。功能，稳定性和能效均不及当前版本。主版本会在将来的更新中添加 Audirvana Plus 的支持。
