### ISSUE TITLE
Chinese or Wrong lyrics

### ISSUE THREAD

**Issue by TonariInc** [ddddxxx/LyricsX#129]
Hi, 
nice lyrics program... 
but it shows wrong lyrics, and chinese lyrics.
is there a way to control the language?

john

**Comment by ddddxxx** [comment]
Hi.
For wrong lyrics, you can click “Search Lyrics” from status bar menu to search manually.
For language control, uncheck “Prefer Bilingual Lyrics” from preferences window.
