### ISSUE TITLE
1.3.0-beta 版本不定时崩溃

### ISSUE THREAD

**Issue by kysoft** [ddddxxx/LyricsX#135]
[LyricsX_crash.zip](https://github.com/ddddxxx/LyricsX/files/1844024/LyricsX_crash.zip)
软件中使用中出现不定时崩溃的问题，附件是 .crash 文件
崩溃时未对软件做特定操作，只是在搭配 iTunes 正常使用。

**Comment by kysoft** [comment]
[crash.zip](https://github.com/ddddxxx/LyricsX/files/1868451/crash.zip)
更多相关文件

**Comment by ddddxxx** [comment]
崩溃记录中有多个问题

- [x] 搜索窗口没有正确 release
- [ ] 新加入的逐字歌词没有正确初始化
- [ ] 与播放器通信时发生问题（似乎不是在 v1.3.0 引入的）

**Comment by ddddxxx** [comment]
1.3.0-beta.2 已发布，解决了最频繁的几个问题。应当可以正常使用了

**Comment by 900202eric** [comment]
1.3.0-beta.2 好像無法進行搜尋歌詞，繁簡中文轉換功能正常

**Comment by ddddxxx** [comment]
@900202eric 新版本确实修改了搜索窗口，而且我也无法在 macOS 10.12 上测试。

我再研究一下……建议新开一条 issue 以便跟踪问题。

**Comment by kysoft** [comment]
感谢跟进，更新到 1.3.0-beta 2 后，持续播放 100 首歌曲测试，没有发生崩溃现象，可以稳定使用了；搜索功能在 macOS 10.13.4 上工作良好。

**Comment by jonise92** [comment]
GitHub版本目前使用正常  但是商店下的用不成
