### ISSUE TITLE
當設置中文繁體時，設定常常跑回簡體中文。

### ISSUE THREAD

**Issue by Steven0811** [ddddxxx/LyricsX#136]
每次設定成中文繁體時，下次再打開 LyricsX 雖然設置當中是繁體中文，但歌詞都是簡體中文，需要重新設定才會恢復正常。

**Comment by ddddxxx** [comment]
dupl #125 

v1.3.0-beta 已修复。你可以从 GitHub 下载，或等待正式版更新。
