### ISSUE TITLE
1.2.3 from MAS won't launch after macOS and Xcode upgrade

### ISSUE THREAD

**Issue by lldsolitude** [ddddxxx/LyricsX#137]
Version 1.2.3 from Mac App Store won't launch after upgrade to macOS 10.13.4 and Xcode 9.3.
Error message from console:
`dyld: Symbol not found: __T0s14_VaListBuilderC15gpRegistersUsedSivpWvd
  Referenced from: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftos.dylib
  Expected in: /Applications/LyricsX.app/Contents/MacOS/../Frameworks/libswiftCore.dylib
 in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftos.dylib
Abort trap: 6`
Seems like the app is trying to reference dynamic library from Xcode again.

**Comment by ddddxxx** [comment]
v1.2.3 or v1.3.0-beta？

**Comment by lldsolitude** [comment]
Just updated, it was 1.2.3 from Mac App Store

**Comment by ddddxxx** [comment]
[1.3.0-beta](https://github.com/ddddxxx/LyricsX/releases/tag/v1.3.0-beta) should have fixed this.

**Comment by lldsolitude** [comment]
Indeed, thanks.
