### ISSUE TITLE
歌词显示在屏幕正中……

### ISSUE THREAD

**Issue by zhyiyu** [ddddxxx/LyricsX#139]
老铁，Karaoke 歌词显示在屏幕正中央，还没法调整，怎么办？

![image](https://user-images.githubusercontent.com/26550166/38201596-dd9d6f20-3666-11e8-9b72-9b3f5978d76b.png)

**Comment by ddddxxx** [comment]
你可以在 Preferences -> Display -> Spacing to screen edge 调整 Karaoke 歌词的位置。（四条红线可以点击，以设置约束是否生效）

**Comment by zhyiyu** [comment]
原来还要点击红线，多谢啦。
