### ISSUE TITLE
OSX 10.13.4 (17E199)无法使用

### ISSUE THREAD

**Issue by take7yo** [ddddxxx/LyricsX#140]
升级了OSX后无法打开。
![image](https://user-images.githubusercontent.com/3365568/38298926-52d21906-382b-11e8-92e3-a8e9a2f90309.png)
![image](https://user-images.githubusercontent.com/3365568/38298963-68138e58-382b-11e8-9fe0-c9b443517c69.png)

**Comment by bzq2810** [comment]
@ddddxxx 10.13.4下MAC目前最新版本无法打开
更新v1.3.0-beta后可以打开，**但是点击“显示歌词窗口”依旧闪退。**
