### ISSUE TITLE
1.3.0 beta 2 @ macOS 10.2.1 無法開啟搜尋歌詞視窗

### ISSUE THREAD

**Issue by 900202eric** [ddddxxx/LyricsX#142]
打開後，其餘功能正常，惟搜尋視窗會一閃而過，無法顯示
![2018-04-06 10 51 17](https://user-images.githubusercontent.com/18681371/38401464-7a8719f2-3988-11e8-826f-cd362c891ae6.png)

**Comment by ddddxxx** [comment]
请尝试一下[这里的版本](https://github.com/ddddxxx/LyricsX/issues/145#issuecomment-379625705)

**Comment by ddddxxx** [comment]
1.3.0 正式版已发布，请确认问题是否依然存在

**Comment by ddddxxx** [comment]
closing due to lack of feedback.
