### ISSUE TITLE
Menu Bar 的歌詞可否顯示成繁體中文的格式

### ISSUE THREAD

**Issue by 900202eric** [ddddxxx/LyricsX#149]
menu  bar 的部份能否將簡體中文改成能選擇繁體中文，卡拉ok模式的繁體中文已能常駐
<img width="267" alt="2018-04-14 11 57 45" src="https://user-images.githubusercontent.com/18681371/38770082-ce4ffa46-403f-11e8-808d-4bf7f728c8d1.png">

**Comment by ddddxxx** [comment]
最近刚修复这个问题。1.3.0 正式版就可以看到了:)

**Comment by 900202eric** [comment]
OK，此外1.3.0 beta2 版本，好像一次快轉太多歌就會crash

**Comment by 900202eric** [comment]
[LyricsX_2018-04-15-000031_huangweichende-MacBook-Pro.crash.zip](https://github.com/ddddxxx/LyricsX/files/1910582/LyricsX_2018-04-15-000031_huangweichende-MacBook-Pro.crash.zip)

**Comment by ddddxxx** [comment]
这是已知问题，还没有头绪，但是来不及修了。系统更新后1.2.3大范围崩溃，需要尽快发布1.3.0。

无论如何，感谢反馈。

**Comment by 900202eric** [comment]
好的，不會造成問題啦，辛苦了！
