### ISSUE TITLE
希望把双行显示充分利用起来，增强对双语歌词的支持度

### ISSUE THREAD

**Issue by GarboHeart** [ddddxxx/LyricsX#151]
自己制作的双语歌词导入后双行显示起来总是会错位，要不就是上一句的中文+下一句的英文，或者两行全是中文或者英文，调试成单行显示，也不是单纯的显示英文或者中文，而是中英混合显示。而我用1.1.10旧版本版，同样的歌词单行显示可以单独显示中文，而不至于错乱，所以歌词本身是没问题的，应该是显示的规则问题。

另外，歌词的黑条阴影框的高能否在调小一点，比起之前太占屏幕位置了。

**Comment by ddddxxx** [comment]
可否上传你制作的双语歌词？由于歌词模型中译文是绑定在每一行歌词上的，你说的情况是因为歌词没有正确解析，而不是显示错位。

关于背景，我认为目前可定制内容已经足够多了，如果连边距都能调整，未免太过繁琐。歌词的背景框是按照字体设置的。请问你是否调整过字体？某些字体的字面较小，或许还有优化空间。

**Comment by ddddxxx** [comment]
P.S. 本项目从未发布过 1.1.10 版本，你说的可能是另一个项目 MichaelRow/Lyrics。在代码上，本项目与其并没有继承关系。

**Comment by ddddxxx** [comment]
closing due to lack of response.
