### ISSUE TITLE
希望歌词来源能添加genius，国内歌词英文各种屏蔽很烦人。

### ISSUE THREAD

**Issue by thevenomsnake** [ddddxxx/LyricsX#153]
希望能增加genius上的歌词，国内歌词英文各种屏蔽很烦人。当然只是一个提议，如果您觉得有兴趣，我非常高兴能看见新增歌词来源有genius。

**Comment by ddddxxx** [comment]
你好，我非常愿意增加新的歌词源。但这可能比你想象的要复杂。一个歌词源需要有公开的 API，提供带有时轴的歌词。而且，LyricsX 这种允许用户自行管理未加密的歌词文件的做法违反了大多数服务提供商的 TOS。

Genius 确实提供了 API，但是：
1. 需要用户登陆账号
2. 不提供时轴
3. 违反 TOS

**Comment by ddddxxx** [comment]
close due to inactivity
