### ISSUE TITLE
请问mac可以不可以在屏幕顶部显示呢？

### ISSUE THREAD

**Issue by jacobzhou** [ddddxxx/LyricsX#158]
或者能支持拖动更好，谢谢

**Comment by jacobzhou** [comment]
知道了

**Comment by ddddxxx** [comment]
当前版本已可以按边距调整位置。关于拖动歌词窗口，你可以尝试这里的版本： https://github.com/ddddxxx/LyricsX/issues/57#issuecomment-387021450

**Comment by ddddxxx** [comment]
close due to inactivity
