### ISSUE TITLE
macOS Mojave 下 Spotify 闪退

### ISSUE THREAD

**Issue by zifchen** [ddddxxx/LyricsX#160]
一打开 LyricsX 就会导致 Spotify 闪退

**Comment by ddddxxx** [comment]
LyricsX 和 Spotify 的进程是完全隔离的，仅通过 AppleEvent 交流。理论上 AppleEvent 并没有使目标程序崩溃的能力。
对于 Spotify 的问题，我也无能为力。这也可能是 Mojave 导致的，正式版发布后如果还有问题，我会继续跟进。

**Comment by zifchen** [comment]
那可能是 AppleEvent 的问题？因为正常播放的 Spotify 一打开 LyricsX 或者是 Musixmatch 都会闪退，或者开着 LyricsX 或者 Musixmatch 时，一打开 Spotify 也会闪退。

**Comment by kikandychan** [comment]
我也存在这个情况，所有可以读取Spotify播放状况的app都会导致crash，不止lyrics，还包括一众同步到last.fm播放记录的和在状态栏显示Spotify当前播放曲目的apps都会导致Spotify crash

**Comment by zifchen** [comment]
更新 Beta 2 之后就不会闪退了 试试看？

**Comment by ddddxxx** [comment]
Mojave 正式版无此问题
