### ISSUE TITLE
Could you please add support for iTunes music video?

### ISSUE THREAD

**Issue by stutterrrrer** [ddddxxx/LyricsX#166]
Whenever I play music Video on iTunes Mac,
LyricX fails to automatically fetch lyrics, and I'd have to manually search for it.

I have the habit of floating the video window while doing something else,
so the floating window is quite small and so I don't want to take up the window space with buil-in lyrics in iTunes.

So I'm in desperate need for lyrics support for music videos.
Thank you.

**Comment by stutterrrrer** [comment]
Sorry,
* window is quite small

**Comment by ddddxxx** [comment]
iTunes provides following kinds of media. Currently I ignore other media except `song`s.

- alertTone
- audiobook
- book
- homeVideo
- iTunesU
- movie
- song
- musicVideo
- podcast
- ringtone
- tvShow
- voiceMemo
- unknown

Supporting `musicVideo` is reasonable and (technically) easy. This can be done in the next version.
