### ISSUE TITLE
10.14 Beta 下打不开

### ISSUE THREAD

**Issue by wu-yu-li** [ddddxxx/LyricsX#167]
在10.14 Beta (18A336e)下无响应。

**Comment by ddddxxx** [comment]
是无响应还是打不开？在`活动监视器.app`里能看到进程吗

**Comment by volzkzg** [comment]
在 10.14 (18A371a) 上目前是可以工作的。

**Comment by wu-yu-li** [comment]
10.14 Beta (18A365a) 可以工作。
