### ISSUE TITLE
wrong song match with audirvana plus integration mode (+itunes) 

### ISSUE THREAD

**Issue by kimklai** [ddddxxx/LyricsX#171]
audirvana plus 3.2.5 (3137)
LyricsX 1.3.1

When playing with audirvana plus integration mode + itunes, LyricsX failed to get correct song title.
If I manually search the song and apply it, everything works.
If shift to next song, LyricsX will stuck on previous song.

- LyricsX is set on audirvana.
- Audirvana's preferences has set deactivated itunes playback / volume control etc. to gain sound improvement by pre-bufferring.

Any idea ? or how to turn on debug mode ? I can help to debug & fix it if more developing info provided.

Thanks

**Comment by ddddxxx** [comment]
It works good to me (audirvana plus 3.2.6). Do you have Xcode installed so that I can run some code on your device?

And please don’t search manually when LyricsX stuck on previous song. The app will save lyrics for previous song, and mass up your database.

**Comment by ddddxxx** [comment]
The app queries current track’s information via AppleScript. It’s terribly inefficient due to a bug caused by Apple. Therefor the app only performs the query when Audirvana “tell” it that current track is changed.

It seems the app didn’t receive the notification on your device. So it thought the track remains unchanged.

(Quit LyricsX and reopen may be helpful)

**Comment by kimklai** [comment]
沒注意可以用中文, 哈.

額外測試單獨使用audirvana是正常的，但掛上itunes integration mode就壞了。有抓到曲名，但沒抓到時間軸；或是反復一直跳出曲名畫面，而不會續繼下去。
我有xcode可以測試，本來想試編LyricsX，但目前還卡在cartfile的framework編不過。
你說的apple script是哪個檔? 我先看script是否正常...

**Comment by ddddxxx** [comment]
关于音乐播放的部分在这个repo： https://github.com/ddddxxx/MusicPlayer 。Carthage编译失败也是因为这里，以release模式编译会导致编译器崩溃😅，你可以手动build一次然后放进`Carthage/Build`文件夹。

没有抓到时间轴就更奇怪了……请试试在`Script Editor`中运行以下脚本，应该会输出当前的播放进度。

```
tell application "Audirvana Plus" to get player position
```

**Comment by ddddxxx** [comment]
已确认开启 itunes integration mode 且关闭 itunes playback / volume control 时 audirvana 不会发送状态变化的通知。若要修复，需要频繁通过 Apple Script 查询播放器状态。对能耗影响较大。仅开启 itunes integration mode 时一切正常。

由于涉及的改动较大，有诸多不利影响，且 itunes integration mode 被标记为 legacy 功能。LyricsX 不会支持此种情形。
