### ISSUE TITLE
无法进入设置，无法正常退出

### ISSUE THREAD

**Issue by wangshy** [ddddxxx/LyricsX#174]
试过https://github.com/ddddxxx/LyricsX/issues/120 讨论中的几个版本，现象基本类似： 打开lyricsx，打开spotify，歌词可以显示，但无法找到设置菜单，无法对lyricsx做任何操作；然后关闭spotify，lyricsx也消失，再次打开spotify或试图点击lyricsx应用程序无任何反应。只有activity monitor手动杀掉lyricsx进程后才能再次打开。
无crash log.
Mac：10.13.6 
Xcode 10.0
Build version 10L221o

**Comment by ddddxxx** [comment]
但无法找到设置菜单是指？是 #159 的情况吗？

**Comment by wangshy** [comment]
最新的1.4.1没问题了。
这软件真棒👍

**Comment by ddddxxx** [comment]
喜欢的话请点右上角的star😆
