### ISSUE TITLE
Touch Bar无法显示歌词

### ISSUE THREAD

**Issue by thevenomsnake** [ddddxxx/LyricsX#176]
系统版本macOS Mojave 10.14 beta
重启软件，重新勾选，均无效。勾选按钮后，Touch Bar音乐波浪标志变成了歌词标志并且处于亮的状态。但是点击无效。

**Comment by ddddxxx** [comment]
常驻 Touch Bar 的接口是非公开的。Apple 可能在系统更新中修改了该接口的行为。

我没有用于测试的 10.14 系统，正式版发布后我会测试跟进。

**Comment by thevenomsnake** [comment]
感谢并期待
