### ISSUE TITLE
LyricsX_1.4.1+1846不支持OS X10.11.6么？启动无反应

### ISSUE THREAD

**Issue by zhangyongbo** [ddddxxx/LyricsX#177]
LyricsX_1.4.1+1846不支持OS X10.11.6么？启动无反应

**Comment by ddddxxx** [comment]
支持的。请在活动监视器中确认程序是否运行。并[检查是否有崩溃记录](https://github.com/ddddxxx/LyricsX/issues/120#issuecomment-346722246)

**Comment by zhangyongbo** [comment]
活动监视器中只有LyricsXHelper在运行。

**Comment by zhangyongbo** [comment]
这是崩溃纪录
Process:               LyricsX [4078]
Path:                  /Applications/LyricsX.app/Contents/MacOS/LyricsX
Identifier:            ddddxxx.LyricsX
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           LyricsX [4078]
User ID:               501

Date/Time:             2018-09-14 11:45:41.362 +0800
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        437D6A78-EABE-2907-CA7B-2B7BFF31E7F8


Time Awake Since Boot: 10000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
  Referenced from: /Applications/LyricsX.app/Contents/MacOS/LyricsX
  Reason: image not found

Binary Images:
    0x7fff61278000 -     0x7fff612afa47  dyld (360.22) <6B9CD3BA-2D60-3629-A0CB-AB810F55E8DD> /usr/lib/dyld

**Comment by ddddxxx** [comment]
了解了。项目中引用的 `DFRFoundation.framework` 只有 macOS 10.12.2 及更高版本才有。

下一版本修复。
