### ISSUE TITLE
關於振り仮名(furigana)顏色的設置

### ISSUE THREAD

**Issue by Windypper** [ddddxxx/LyricsX#180]
當勾選了 'lab' 中的 'Automatically generate furigana for Japanese lyrics' 後日本漢字上顯示的振り仮名不會跟隨 ‘display' 中 'lyrics’ 的顏色設置而改變，而是保持黑色，可能造成可讀性較差的情況，所以希望增加設置振り仮名顏色的選項，謝謝。
![image](https://user-images.githubusercontent.com/30546031/45664746-20f49100-bb40-11e8-93ab-b12edd38d00e.png)

**Comment by ddddxxx** [comment]
这是已知的问题：用于渲染振り仮名的 [CTRubyAnnotation](
https://developer.apple.com/documentation/coretext/ctrubyannotation) 不跟随文本颜色且不能调整。我认为这是 Apple 的问题。

作为开发者，我有一个别扭的办法可以“修复”这个问题：将文字渲染为图片，然后将这张图片作为蒙版添加到色块上。这样做相当麻烦，且会导致额外的性能开销。

最好的情况是 Apple 解决这个问题。总之，短期内我不会考虑修复。

无论如何，感谢反馈。我并不会日语，也不听日文歌。如果当前振り仮名的功能有任何地方不符合日语习惯，请不吝赐教。

**Comment by Windypper** [comment]
原來是 Apple 的問題，那只能希望 Apple 可以解決了。謝謝及時的回覆 : D

**Comment by shulan-moe** [comment]
因为比较好奇这个问题，前几天我向Apple询问了有关`CTRubyAnnotation`生成的字符设置字体和颜色的问题。
Apple的回复如下，供参考：

> Apple Developer Relations
> 
> Engineering has provided the following information regarding this issue:  
>
> The API CTRubyAnnotationCreateWithAttributes() supports passing kCTForegroundColorAttributeName.

**Comment by ddddxxx** [comment]
@shulan-moe 可以用，非常感谢！

这里是我的失误了，CoreText不依赖Foundation，确实不应该用NSAttributedStringKey。当时试了一下其它的key，碰巧某些有效，就甩锅给Apple了。

我会尽快更新。

**Comment by frankzhang05** [comment]
最近使用的时候发现了相同的问题，所以重开一下……

如图，这是没有卡啦OK歌词、只有每行时间的效果：
<img width="50%" src="https://user-images.githubusercontent.com/25704248/89122664-a480b680-d4fb-11ea-93df-2728ce062489.png" alt="非滚动歌词" />
可以看到，furigana和歌词的颜色不同。

然而，在滚动歌词中则没有这个问题：
<img width="50%" src="https://user-images.githubusercontent.com/25704248/89122741-66d05d80-d4fc-11ea-97df-3ecd7396f3a5.png" alt="滚动歌词" />
（虽然没有唱到的歌词颜色还是不对）

不知道是否为软件问题？个人对macOS开发不是很了解，所以不太清楚为什么……多谢！
