### ISSUE TITLE
“优先使用歌词源”问题

### ISSUE THREAD

**Issue by ILOFI** [ddddxxx/LyricsX#182]
设置了优先使用歌词源后出现匹配错误歌词现象。“优先使用”应保证在 歌曲名 与 歌手 相同的情况下再选择优先的歌词源。

App Store Version 1.3.1(1702)

**Comment by ddddxxx** [comment]
这个选项是歌词排序不完善时的折衷方案。经过数个版本的优化，我认为目前的排序已经能让人满意。

此功能不会得到更新，并可能在将来的版本中被删除。
