### ISSUE TITLE
如何解决无法找到本地.lrc文件

### ISSUE THREAD

**Issue by YuguangZh** [ddddxxx/LyricsX#188]
我现在我有test.mp3和test.lrc都在同一个文件夹内，但是当我用iTunes打开test.mp3的并不会再LyricsX中加载。请问如何解决？

已经勾选加载同名歌词，歌词文件保存地址已经改为储存test.lrc的文件中。
当播放其他歌曲时，自动搜索歌词和显示均正常。

补充：找到一个临时解决办法，在歌词窗口中可以手动拖拽。

谢谢

**Comment by ddddxxx** [comment]
请问歌曲文件的位置？由于沙盒限制，应用只能读取自身的文件，以及（提前声明过的）Music文件夹下的内容。

**Comment by ChikoritaPiplup** [comment]
> 请问歌曲文件的位置？由于沙盒限制，应用只能读取自身的文件，以及（提前声明过的）Music文件夹下的内容。

您好，我现在也遇到了这个问题。
我的文件在music/歌手名/专辑名/   这个目录下，flac文件和lrc文件都在这里，并且已经手动改为同名。
但是在播放的时候，依旧无法识别本地歌词文件，他会去在线搜索，而我很多歌是没有在线歌词的。
现在的临时解决方案是拖动到歌词窗口里，然后他会在对应目录下再新建一个lrcx文件。
有没有办法直接让他读取lrc文件呢？

**Comment by ddddxxx** [comment]
@ChikoritaPiplup 请问应用版本？1.4.3 及以前的版本会优先读取 lrcx 文件。这是为了让之前的用户享受到新的逐字歌词。1.4.4已经修复了。
另外只有 iTunes 和 VOX 才支持读取同名歌词文件。请问你使用的是什么播放器？

**Comment by ddddxxx** [comment]
更新：已确认这部分逻辑有问题，只要读取到的歌词后缀为lrc，就会重新搜索。我会尽快修复

**Comment by ChikoritaPiplup** [comment]
@ddddxxx 播放器为Audirvana plus 3.2.14，Lyricsx版本为1.44(1986)，系统版本10.14.2
后来我将同名lrc文件都放到了lyricx设置里的“歌词文件保存地址”打开的目录下了（music/Lyricsx）
不过还是无法识别，会在线搜索
大概不是播放器种类的问题
期待你的更新 : )

**Comment by ddddxxx** [comment]
注意 Audirvana Plus 不支持读取歌曲文件夹下的同名歌词（选中 Audirvana Plus 后该选项为灰色）。这是因为该播放器不提供当前歌曲文件的位置。
