### ISSUE TITLE
No option to configure position of karaoke lyrics after update

### ISSUE THREAD

**Issue by jahirfiquitiva** [ddddxxx/LyricsX#193]
Hello

I recently updated to the latest version, but now there's no option to configure position of karaoke lyrics after update, as there was before.

Please add it back. Thanks

**Comment by ddddxxx** [comment]
check Preferences -> Display -> Karaoke -> Draggable, then you can drag karaoke lyrics freely.

please let me know if you find any syntax error or vague expression.

**Comment by jahirfiquitiva** [comment]
@ddddxxx That didn't work ...

Also, you might want to change the "draggable" word. It means that you can move the thing freely in the window, but like when clicking on it, and then moving the mouse to position it wherever you want.
That's what I understood.

**Comment by jahirfiquitiva** [comment]
Not intuitive at all but just discovered how to do it.
