### ISSUE TITLE
最新系统提示无法打开“LyricsX.app”，因为无法确认开发者的身份。

### ISSUE THREAD

**Issue by niices** [ddddxxx/LyricsX#195]
系统macOS Mojave 10.14 (18A391)
安全性与隐私已开启所有来源
![image](https://user-images.githubusercontent.com/8327775/46846246-9dae1e80-ce11-11e8-8d4f-4884f356ec6a.png)

**Comment by niices** [comment]
已解决
先关闭任何来源 打开一遍就行了

**Comment by ddddxxx** [comment]
这个问题一直都在，但是一直没有头绪。我确实是用付费开发者账号签名了，1.4.2 甚至加入了 Notarized App 的验证。但是一直有用户反馈无法直接打开。

对于用户来说，有个很直接的方法：右键选择打开即可，以后也不会再有警告。但是第一次不能双击打开非常影响体验。有人知道怎么消除这个警告吗？

**Comment by NickZu** [comment]
mojave 10.14.1 第一次打开:需要按住control+单击打开

**Comment by ddddxxx** [comment]
写了FAQ说明这一情况：https://github.com/ddddxxx/LyricsX/wiki/FAQs

**Comment by yuanzhaoyang** [comment]
mac OS Mojava 10.14.4 打不开的问题
1. 先关闭任何来源 打开一遍 —— 无法解决
2. 按住control+单击打开 —— 无法解决
3. 右键选择打开即可 —— 成功打开
