### ISSUE TITLE
problem saving custom lyrics in newest version

### ISSUE THREAD

**Issue by TheScottMan** [ddddxxx/LyricsX#199]
Hi, thanks so much for creating LyricsX, i LOVE it and use it all the time. and the new version is GREAT, except for a couple of problems...

(1) I created some lyrics on my own and drag/drop to the lyrics window while playing the song and the lyrics display and work great. A properly formatted version is even saved in the LyricsX lyrics folder along with all the other. However, if ever I play the song again the lyrics do not display and says "missing/no lyrics", even with the correct file in the Lyrics folder. All other songs play correctly, just not the one i drag-n-drop. Please advise.

(2) I am SOOOOOO happy we can now move the lyrics windows around, even to other screens. This is a MAJOR improvement. However, the windows to not maintain their positions between launches. Please let me know if this is only on my computer this behaviour. Thanks.

(3)  I really wanted to send you a donation but cannot use AliPay (is not available in my country). Can you take PayPal?

**Comment by TheScottMan** [comment]
sorry I forgot to mention...

(4) I would be FOREVER grateful if you could make one compatible OSX 10.8.5 Mountain Lion version! 😁

**Comment by ddddxxx** [comment]
1. I guess you marked wrong lyrics, so the app doesn't read it. Importing lyrics should remove the mark. I'll fix it in the next version. Before that, you can **REMOVE ALL THE WRONG LYRICS MARK** using this command:
```
$ defaults delete ddddxxx.LyricsX NoSearchingTrackIds
```

2. It works fine for me. You can use this command to check the backing value:
```
$ defaults read ddddxxx.LyricsX DesktopLyricsXPositionFactor
$ defaults read ddddxxx.LyricsX DesktopLyricsYPositionFactor
```
the result should reflect the relative position of the window.

3. Thank you so much! Just knowing your will means a lot to me. Please feel free to use the app freely, and tell your friends if possible : )

**Comment by ddddxxx** [comment]
1. I guess you marked wrong lyrics, so the app doesn't read it. Importing lyrics should remove the mark. I'll fix it in the next version. Before that, you can **REMOVE ALL THE WRONG LYRICS MARK** using this command:
```
$ defaults delete ddddxxx.LyricsX NoSearchingTrackIds
```

2. It works fine for me. You can use this command to check the backing value:
```
$ defaults read ddddxxx.LyricsX DesktopLyricsXPositionFactor
$ defaults read ddddxxx.LyricsX DesktopLyricsYPositionFactor
```
the result should reflect the relative position of the window.

3. Thank you so much! Just knowing your will means a lot to me. Please feel free to use the app freely, and tell your friends if possible : )

**Comment by TheScottMan** [comment]
WORKED!! thanks so much... and i figured out the window position problem... it had to do with my changing monitor configurations... fixed now 👍🏼
