### ISSUE TITLE
Touch Bar Center the lyrics

### ISSUE THREAD

**Issue by STayinloves** [ddddxxx/LyricsX#208]
Current lyrics in the touch bar lies on the left side, it would be nice if the "center" option exists.

**Comment by Noneleft-zyx** [comment]
Agreed, I would be so nice to have the "center" option since the font in touchbar is very small. And it would be fantastic to display the name of the current song along with the lyrics.

**Comment by ddddxxx** [comment]
In version 1.4.5, you can center the lyrics by placing 2 flexible spaces arounds the lyrics. Enjoy.

**Comment by chenyanfei-m** [comment]
custom touch bar -> add spacing before and after lyrics
