### ISSUE TITLE
歌詞排序邏輯

### ISSUE THREAD

**Issue by andylee1890** [ddddxxx/LyricsX#211]
經過兩三個月的使用,發現xiami的歌詞常常是不準的,我大部分的手動操作就是使用163的歌詞, 相對而言163的準確率要高壹點, 建議排序把163放在前面, 或者讓用戶自己設置排序
![image](https://user-images.githubusercontent.com/12568851/48760545-3e311180-ece1-11e8-883a-6cef45f841c6.png)
![image](https://user-images.githubusercontent.com/12568851/48760468-f90cdf80-ece0-11e8-8f61-bb2a184c024a.png)

**Comment by yiqinfu** [comment]
我也同意！手动选歌词的时候都是 163 正确率更高。或者麻烦作者把早期版本的“选择默认歌词来源”再放回 app 里面？

**Comment by thevenomsnake** [comment]
我也同意麻烦作者把早期版本的 “选择默认歌词来源” 再放回 app 里面

**Comment by andylee1890** [comment]
我把hosts改掉后還是會出現xiami的歌詞,請問獲取xiami歌詞的真實url是什麼, 我去把它屏蔽掉
![image](https://user-images.githubusercontent.com/12568851/49055369-4a155a00-f232-11e8-94b2-c5a9ade66580.png)
![image](https://user-images.githubusercontent.com/12568851/49055382-54cfef00-f232-11e8-9be6-c84763c1d062.png)

**Comment by yiqinfu** [comment]
好像这个 issue 里都是 Spotify 用户。这样看来 163 相比于虾米收录了更多繁体中文的歌名和华语歌手的英文名。（Spotify 上很多华语歌手的名字都是他们的英文名。）

**Comment by andylee1890** [comment]
@yiqinfu 我主要反映的還是英文歌曲, spotify和163的歌曲名,專輯名,以及歌手名匹配度更高吧

**Comment by andylee1890** [comment]
使用Little Snitch強制禁用xiami.net,xiami.com,果然就沒有出現xiami的歌詞了
![image](https://user-images.githubusercontent.com/12568851/49081772-c9cb1500-f282-11e8-8d19-5aceffcdd59a.png)
![image](https://user-images.githubusercontent.com/12568851/49081782-d2bbe680-f282-11e8-83e0-67ee2d5fdd8b.png)
![image](https://user-images.githubusercontent.com/12568851/49081864-17e01880-f283-11e8-9694-de9ca89e3f95.png)
![image](https://user-images.githubusercontent.com/12568851/49081905-3514e700-f283-11e8-88dc-d018c86a2189.png)

**Comment by andylee1890** [comment]
![image](https://user-images.githubusercontent.com/12568851/49082038-9c329b80-f283-11e8-91de-e026eca2dee1.png)

**Comment by ddddxxx** [comment]
我还是不愿意放回“选择默认歌词来源”这个选项，未来改进的方向也是希望更好的排序。不过我可以提供关闭特定歌词源的选项，以及“精确搜索”选项（只选择完美匹配的歌词）。
