### ISSUE TITLE
建议能够添加多次播放后不再显示歌词的功能

### ISSUE THREAD

**Issue by zhyiyu** [ddddxxx/LyricsX#217]
希望能够添加一个多次播放后就不再自动显示歌词的选项，因为多次播放后，一般已经比较熟悉歌词了，所以就不再需要显示了。

这个次数可以自定义，如果希望多看几次歌词，可以把这个次数改得大一些。

谢谢！

**Comment by ddddxxx** [comment]
抱歉回晚了。我不打算加入这一功能。我认为关掉软件的主要功能（甚至是唯一功能）没有意义。而且歌词文件对用户是开放的，要储存播放次数等信息有些麻烦。相比投入的精力，这样做的好处实在有限。
