### ISSUE TITLE
开启“自动为日文生成注音”，播放日文歌曲时自动退出

### ISSUE THREAD

**Issue by augusl** [ddddxxx/LyricsX#219]

**Comment by Zer0xPoint** [comment]
同样遇到问题 10.14 itunes audirvana都遇到

**Comment by tianranwangcs** [comment]
10.14.2 iTunes also has the problem.

**Comment by ddddxxx** [comment]
[Enjoy!](https://github.com/ddddxxx/LyricsX/releases/tag/v1.4.4)
