### ISSUE TITLE
匹配歌词时，确保歌词和歌曲名字的相似性

### ISSUE THREAD

**Issue by oscar-c** [ddddxxx/LyricsX#221]
有些歌的歌词还没发布，或者是纯音乐。
这时候LyricX就会匹配到一些很离谱（下图）的结果。有时候一张专辑下来，每首歌都要标记一下错误的歌词。
![离谱结果](https://d.pr/i/5x1rWD+)

希望在匹配之前确保一下歌曲名字和歌词之间有一定程度的相似性。

**Comment by ddddxxx** [comment]
1.4.5 新增“精确搜索”选项，仅使用匹配度达到某个阈值的歌词。
