### ISSUE TITLE
有异常流量占用

### ISSUE THREAD

**Issue by cv0cv0** [ddddxxx/LyricsX#233]
![image](https://user-images.githubusercontent.com/18623780/51421280-183bc680-1bd7-11e9-8c59-29f858345bca.png)

**Comment by ddddxxx** [comment]
如果认为流量过大或有其它疑惑，请提供复现步骤，以便我确认问题。

**Comment by cv0cv0** [comment]
正常使用，发现有几十k持续性的上下传。

发自我的 iPhone

**Comment by ddddxxx** [comment]
未能复现。搜索歌词和获取版本信息都是一次性的，持续流量应该是 Crashlytics 产生的，我也不能控制。
