### ISSUE TITLE
1.4.5無法繁簡轉換

### ISSUE THREAD

**Issue by 900202eric** [ddddxxx/LyricsX#242]
無法繁簡轉換
https://imgur.com/a/7qeDw8G

**Comment by AnthonyDu0122** [comment]
+1！本来就是简体中文的歌曲可以转换成繁体中文，但是外文歌曲的歌词翻译无法转换成繁体中文。

**Comment by ddddxxx** [comment]
和 #244 是同一个问题。会尽快修复
