### ISSUE TITLE
Feature Request: Mark a song as instrumental

### ISSUE THREAD

**Issue by i0ntempest** [ddddxxx/LyricsX#245]
我经常听一些纯音乐，在播放时这个app就会给我找来错误的歌词，标记错误之后它又会找一遍，重复若干次。建议添加一个功能来把某首歌标记为纯音乐，这样会方便不少。

**Comment by ddddxxx** [comment]
标记错误歌词后不会重新搜索。我这边功能是正常的，还请你再确认一次。

**Comment by i0ntempest** [comment]
但是我这经常要标记三四次它才会停止显示，第一次标记错误后隔上几秒钟又开始显示了。（FYI：我设置了快捷键来标记错误歌词）

**Comment by ddddxxx** [comment]
我这边没有问题。标记错误歌词后，菜单中的“歌词”选项会整个变灰，说明当前没有歌词。请确认一下.

**Comment by i0ntempest** [comment]
我这里也没法百分百每次都trigger这个现象，但是这个问题确实存在。最终标记成功的状态下歌词选项确实是灰色的。有什么日志之类的我能贴在这吗？
