### ISSUE TITLE
1.4.5(2075)截图时不能显示，取消勾选“截图隐藏”功能也不生效

### ISSUE THREAD

**Issue by evilhentaro** [ddddxxx/LyricsX#247]

**Comment by ddddxxx** [comment]
偏好 -> 显示 -> 隐藏歌词的三个选项全都坏掉了，重新打开设置菜单就会复原

**Comment by ddddxxx** [comment]
在修复前，可以通过终端指令修改设置：
```
defaults write ddddxxx.LyricsX [设置项] -bool [yes/no]
```
隐藏歌词的三个设置项分别为 `HideLyricsWhenMousePassingBy`，`DisableLyricsWhenPaused` 和 `DisableLyricsWhenSreenShot`。

**Comment by evilhentaro** [comment]
目前暂时解决了，多谢~
