### ISSUE TITLE
Display settings not saved upon changing

### ISSUE THREAD

**Issue by timothyrobb** [ddddxxx/LyricsX#249]
For reference, I'm talking about the following checked boxes on this screenshot, under Preferences, Display, then "Disable lyrics when:"

![image](https://user-images.githubusercontent.com/1174168/52986262-05c5de80-345c-11e9-9409-71a975bc5cbf.png)

If I disable any of these, none of them actually turn off, and when I close the window and go back into the preferences, they are re-enabled again.
Looks like it's not writing the setting to the stored preferences somewhere?

I'm using the latest version:
![image](https://user-images.githubusercontent.com/1174168/52986339-373eaa00-345c-11e9-81ab-d6caa6b8a551.png)

**Comment by evilhentaro** [comment]
丫~你也这样啦？~

**Comment by timothyrobb** [comment]
> 丫你也这样啦？

Sorry, I have no idea what you're saying here. Google translate says it's "Hey, are you like this?", which doesn't really make much sense hahah.
I don't suppose you can phrase your question in English at all?

**Comment by ddddxxx** [comment]
Sorry for delayed response. The connection between interface and backing storage is not done by code, instead, Apple does this for me. I tried to rebind those options, and the problem magically disappear.

PS: @evilhentaro means he had the same problem.
