### ISSUE TITLE
Do you consider to support NeteaseMusic?

### ISSUE THREAD

**Issue by shangjingbo1226** [ddddxxx/LyricsX#256]
Do you consider to support NeteaseMusic? Is there any particular difficulty to support it?

**Comment by ddddxxx** [comment]
LyricsX queries music information via AppleScript, which Netease Music doesn't support. See [FAQs](https://github.com/ddddxxx/LyricsX/wiki/FAQs#q-我希望支持别的播放器) (Chinese only).
