### ISSUE TITLE
能否增加对pine player的支持

### ISSUE THREAD

**Issue by evilhentaro** [ddddxxx/LyricsX#261]
如题
pine player这个播放器界面很优雅，操作逻辑也很通顺，本地播放器，类似vox。加油~~

**Comment by seagle0128** [comment]
Vote +1

**Comment by ddddxxx** [comment]
无法支持，详见[FAQ](https://github.com/ddddxxx/LyricsX/wiki/FAQs#q-我希望支持别的播放器)。
