### ISSUE TITLE
国内被下架的歌曲是不是就搜索不到歌词了

### ISSUE THREAD

**Issue by Pharing** [ddddxxx/LyricsX#266]
spotify上李志的歌找不到对应的歌词了

**Comment by ddddxxx** [comment]
是的，软件直接从音乐服务提供者的服务器上搜索歌词，而且多数服务都和音轨直接关联。一旦歌曲下架，对应歌词也无法下载。部分歌词源没有这样的关联，例如Gecimi，就不受影响。
