### ISSUE TITLE
Support for Audirvana ver. 3.5?

### ISSUE THREAD

**Issue by lacmd** [ddddxxx/LyricsX#267]
Audirvana Plus recently upgraded to ver. 3.5. Lyric X won't work with the new version.

**Comment by shinkiro25** [comment]
Same issue here, we'll deeply grateful if you updated LyricsX to be compatible with the Audirvana 3.5 :)

**Comment by ddddxxx** [comment]
Done in v1.5.0. Enjoy :)

**Comment by shinkiro25** [comment]
Thank you so much!

**Comment by lacmd** [comment]
Thanks!
