### ISSUE TITLE
macOS 10.14.5 点击状态栏图标导致 Touch Bar 控件消失的问题

### ISSUE THREAD

**Issue by Nyim1s** [ddddxxx/LyricsX#277]
自从上次 1.4.5 版本更新后到现在 1.4.6 版本的 Touch Bar 控件还是有点问题

1.4.5 在展开缩进或者切换到别的 Touch Bar 控件的时候有几率整个 Touch Bar 歌词控件消失
1.4.6 版本比上个版本感觉稳定一些，但是每次点击状态栏上的 LyricsX 图标之后整个 Touch Bar 歌词控件就消失再也不显示了，必须关闭程序重新打开才行

并且 1.4.5 1.4.6 两个版本在 Touch Bar 上的播放进度颜色和歌词的颜色都有错位

特别喜欢 Touch Bar 歌词这一块，但是两个版本都有点问题，所以一直在用 1.4.4 版本，虽然不能显示封面和播放控件，但是是最稳定的一个版本，希望作者能修复一下，感谢，辛苦啦❤️

**Comment by ddddxxx** [comment]
已确认 Touch Bar 歌词消失因为同一个 Touch Bar 控件不能同时提供给应用和 Control Strip。已去除 GitHub 版本的应用内 Touch Bar 歌词（即，不手动展开 Control Strip 上的歌词时，切换到 LyricsX 应用，不会在 Touch Bar 上展示歌词）。修复后 Control Strip 歌词不再消失。
