### ISSUE TITLE
Automatic writing to iTunes does not work. 

### ISSUE THREAD

**Issue by Quorum75** [ddddxxx/LyricsX#283]
Hello.

_Preferences -> Lab -> Write lyrics to iTunes -> Automatically_

Lyrics are not written. I need to do it manually.

- Lyrics 1.4.6
- macOS 10.14.5
- iTunes 12.9.5.5

Thanks

**Comment by ddddxxx** [comment]
The app write lyrics to iTunes after lyrics search task finished, and sometimes they don't (as #246 described).

I'll fix it asap.

**Comment by Quorum75** [comment]
Thanks I do appreciate.

**Comment by NextFire** [comment]
Hello! Also not working here:
- LyricsX 1.5.1
- macOS 10.15
- Music 1.0.0.426

Thanks for your work!

**Comment by ddddxxx** [comment]
please try [v1.5.2-beta.1](https://github.com/ddddxxx/LyricsX/releases/tag/v1.5.2-beta.1)

**Comment by NextFire** [comment]
> please try [v1.5.2-beta.1](https://github.com/ddddxxx/LyricsX/releases/tag/v1.5.2-beta.1)

Everything works fine now! (at least on Mojave - I downgraded from Catalina earlier this month...)
