### ISSUE TITLE
歌词错误

### ISSUE THREAD

**Issue by CarterJimmy** [ddddxxx/LyricsX#29]
我使用iTunes播放歌曲（主要以国外R&B，POP为主），可是很多歌曲都出现歌词完全错误（估计是其他同名的歌曲的歌词），当然也有正常的歌曲。希望开发者提高歌曲识别的精准度！
![2017-04-29 17 14 28](https://cloud.githubusercontent.com/assets/7923743/25554071/68a7d960-2cff-11e7-898a-ba1bca8c4ab8.png)

**Comment by XQS6LB3A** [comment]
歌词是依照歌手和歌名搜索的。图中的情形是由于歌手名被翻译过，会干扰搜索结果（因为歌词库中只有Ed Sheeran的歌词，而没有エド・シーラン的歌词。程序也无法自动将这两个名字关联起来）。类似的情形还有 #20 。
在程序上解决这个问题是很困难的，这个问题在开发中的优先级也很低。

在解决之前，请手动通过正确的歌手名进行搜索。

**Comment by CarterJimmy** [comment]
原来如此，谢谢。

**Comment by oscar-c** [comment]
有些歌词会提供“专辑”的信息，我觉利用这个信息来进一步提高准确率。

仔细来说，有些艺术家会在两张专辑里面，发布一首歌的两个版本。这两个版本的歌词稍微会有区别。如果能比较歌词中自带的 `[al:]` tag，是能够正确选择的。目前看来软件只会选中第一个找到的歌词，所以有时候会找到错误的歌词。

**Comment by XQS6LB3A** [comment]
@oscar-c 很好的建议，我会仔细考虑。

还有另一个改进方案。自动搜索歌词时，对于每一个歌词源，只加载第一条结果。可以稍微提高性能。由于正在开发的 LyricsX for iOS 使用了相同的歌词模块，这个方案还有减少流量消耗的优势。

**Comment by zhuqh93** [comment]
我发现搜索功能有瑕疵，很多英文歌匹配到的都是TTPod源的，然而TTPod资源很少（导致自动使用的歌词一般都是同歌手不同歌名）， 只能手动搜索相匹配的然后才能使用。建议优先用163源，163的资源相对丰富很多，歌词还有翻译和专辑封面，时间轴也做的很好（应该有校对过）。尝试过实验功能-优先使用歌词源：163，但是问题并没有解决，163源的优先等级并没有提升，上面提到的问题还是存在（应该是实验性功能还没有完善），希望@ddddxxx作者能修复。

**Comment by guahsu** [comment]
Hi, 有個想法..是否可參考到歌詞來源的總秒數，或是在提供自選歌詞的部分可以顯示到總秒數讓挑選時比較不會選錯，動態歌詞的秒數我想也會有準確性的提升～昨天才找到這好物，謝謝您的開發：）！

**Comment by ddddxxx** [comment]
@guahsu 你好，感谢建议：）！事实上现在已经根据毫秒数来搜索歌词了，但是有一个问题：所有的歌词源都不是开放接口，而是破解而来，因此元数据缺失。再加上各平台歌词良莠不齐，甚至根本没有总秒数。因此不便作为参考。

**Comment by ddddxxx** [comment]
关于翻译造成的搜索问题，请在 #20 中讨论。其它问题和建议请新开一条issue。
