### ISSUE TITLE
新版Spotify监测不到歌曲名，不自动下载歌词

### ISSUE THREAD

**Issue by Lewesyru** [ddddxxx/LyricsX#294]
貌似是Spotify更新了，目前1.5.0版本搜索歌词时无法自动检测歌名和歌手，也没办法自动下载新歌词了。歌词文件夹里只有一个「 - .lrcx」文件。
Spotify的版本是1.1.12.451.gdb77255f。
OS是macOS 10.13.6 (17G7024)。

**Comment by mediter** [comment]
Setting Spotify as Preferred Music Player via LyricsX Preference seems to solve this problem for me.

Spotify 1.1.14.475.g566c8beb
macOS Catalina 10.15 Beta (19A546d)

**Comment by Lewesyru** [comment]
> > 貌似是Spotify更新了，目前1.5.0版本搜索歌词时无法自动检测歌名和歌手，也没办法自动下载新歌词了。歌词文件夹里只有一个「 - .lrcx」文件。
> > Spotify的版本是1.1.12.451.gdb77255f。
> > OS是macOS 10.13.6 (17G7024)。
> 
> Setting Spotify as Preferred Music Player via LyricsX Preference seems to solve this problem for me.
> 
> Spotify 1.1.14.475.g566c8beb
> macOS Catalina 10.15 Beta (19A546d)
> 
> @Lewesyru

Seems like it is a problem with Spotify. I update my Spotify to 1.1.14.475.g566c8beb and this problem solved.

Thanks.
