### ISSUE TITLE
能否读取本地歌词

### ISSUE THREAD

**Issue by CAUCHY2932** [ddddxxx/LyricsX#296]
我可能需要本地歌词的读取和显示。

**Comment by ddddxxx** [comment]
目前只能读取指定位置的歌词（设置歌词文件保存地址）以及歌曲文件同目录下的同名歌词文件（勾选加载同名歌词）。未来会加入更多对文件存取路径的控制。

**Comment by CAUCHY2932** [comment]
好的，多谢您的积极回答，希望产品能够越来越好，您的产品真的对我帮助很大！
