### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by Quorum75** [ddddxxx/LyricsX#297]
Hi.

The auto update downloads the new version 1.5.1 but then the window "Installing update" froze.

<img width="468" alt="Screenshot 2019-09-16 at 18 30 46" src="https://user-images.githubusercontent.com/49731083/64975780-1b936900-d8b0-11e9-83d2-ef02e41acae0.png">

macOS 10.14.6

**Comment by volzkzg** [comment]
Same here.

**Comment by 52mzd** [comment]
我这里也是哦。

**Comment by Quorum75** [comment]
Finally I downloaded the Mac Appstore version. No problem there.

**Comment by ddddxxx** [comment]
The auto update feature is provided by [Sparkle](https://github.com/sparkle-project/Sparkle). I have very little control over it, and I'm not going to rewrite it myself.

If you have problems during update process, please download manually from [Github Releases](https://github.com/ddddxxx/LyricsX/releases/latest). Sorry for the inconvenience.
