### ISSUE TITLE
Lyrics timeline is not accurate 关于iTunes歌词时间轴对不准的问题（Position 误差）

### ISSUE THREAD

**Issue by MikeWang000000** [ddddxxx/LyricsX#299]
System: macOS Mojave 10.14.6
iTunes: 12.9.5.5
　

**症状・Symptom：**
　　不论如何调整歌词偏移，播放一段时间后，自己就会发生时间错位。甚至会倒回，重新显示刚唱完的歌词。
　　No matter how you adjust the lyrics offset, lyrics timeline become inaccurate after playing for a while. It will even rewind - re-displaying the lyrics that have just been sung.
　
　
**探究・Explore：**
　　打开iTunes播放音乐，在终端输入以下代码。
　　Open iTunes to play music and enter the following code in the terminal.

```
while true
do
    osascript -e 'tell application "iTunes" to player position'
done
```
　

**终端显示内容：
Terminal display content:**

```
10.644000053406
10.644000053406
10.644000053406
10.644000053406
10.644000053406
10.644000053406
10.644000053406
10.644000053406
10.644000053406
10.644000053406
11.642000198364
11.642000198364
11.642000198364
11.642000198364
11.642000198364
11.642000198364
11.642000198364
11.642000198364
11.642000198364
11.642000198364
12.663999557495
12.663999557495
12.663999557495
12.663999557495
```

**结论・Conclusion：**
　　可知 iTunes 在播放时，返回的时长不是实时更新的，存在±1s的误差。
　　但是在歌词显示中，这个误差算很大的了，尤其是在卡拉OK模式下。
　　It can be seen that when iTunes is playing, the returned time is not updated in real time, and there is an error of ±1 s.
　　But in the lyrics display, this error is quite notable, especially in karaoke mode.

　　但是，经过测试，iTunes处于暂停状态时，返回的时长是十分精准的。
　　However, after testing, iTunes in paused state returns a very accurate elapsed time.

```
tell application "iTunes" to pause
tell application "iTunes" to player position
```

　　LyricsX 可能是在 iTunes 播放的时候，定时重新获取了播放时长，得到了有误差的数据，导致歌词时间轴反复错位。
　　Probably LyricsX re-acquires the playback time at intervals when iTunes is playing, and got error data, which caused the lyrics timeline to be repeatedly misaligned.

**建议・Recommendation：**
　　我建议 LyricsX 关闭在播放时定时校对时长的功能；
　　或者加入判断：重新获取的时长，与原播放时长相比差距在1.5s以内，则不作任何反应。
　　I recommend LyricsX to turn off the function of timing correction during playback;
　　Or join the judgment: If the length of re-acquisition is less than 1.5s compared with the original playing time, make no changes.

　
**最后・Finally：**
　　非常感谢作者的辛苦付出！这是我最喜欢的macOS App之一。
　　Many thanks to the author for the hard work! This is one of my favorite macOS apps.

**Comment by ddddxxx** [comment]
非常感谢！！LyricsX 确实有定时校对播放时长。这是为了应对用户拖动时间轴的状况。我也设置了 tolerate（0.1秒），只是没想到 iTunes 给出的结果误差这么大。

会尽快修复。不过目前正在对底层进行重构，更新不会太快。

**Comment by MikeWang000000** [comment]
感谢作者！这个App真的很棒，双语选项、日文振假名注音功能都很实用，作者辛苦了！

**Comment by ddddxxx** [comment]
tolerate 已改为1.5秒，实测不再发生时轴跳动问题。
