### ISSUE TITLE
歌词可能需要一点额外的正则清理？

### ISSUE THREAD

**Issue by Naville** [ddddxxx/LyricsX#301]
![image](https://user-images.githubusercontent.com/5205699/66403601-6f115680-ea19-11e9-93e7-e85540c7cddc.png)
看着像原始来源是带注音的没清理干净。

另: 可否增加写入itunes时保留lrc时间戳的选项或单独导出lrc的功能

**Comment by ddddxxx** [comment]
原始歌词中包含连续的时间标签<180><190>，导致解析失败。会尽快修复。

**Comment by dingyx99** [comment]
歌词还有一个问题，就是来自QQ音乐的歌词会在换行的地方带上//，不仅是歌词展示，写入iTunes中也会把这个带上。
![截屏2019-10-1618 13 55](https://user-images.githubusercontent.com/11485117/66910213-ba8eba80-f040-11e9-8b6b-64c19f5a4c68.png)
![image](https://user-images.githubusercontent.com/11485117/66910274-d72af280-f040-11e9-831e-6001ce49dffa.png)
![截屏2019-10-1618 15 09](https://user-images.githubusercontent.com/11485117/66910309-e4e07800-f040-11e9-9722-cbb04b9f28d5.png)

**Comment by ddddxxx** [comment]
v1.5.2 已修复。

@dingyx99 已过滤QQ音乐中的“//”，会随下一版本发布。
