### ISSUE TITLE
歌词搜索的结果集

### ISSUE THREAD

**Issue by ABUGADAY** [ddddxxx/LyricsX#305]
现在歌词搜索的默认结果集是网易云优先吗？实测虾米的比较优秀，能够正常显示进度
切换歌词源后第一句进度的显示会有偏移
以上反馈实测于touchBar歌词

**Comment by ddddxxx** [comment]
有一个[相当简陋的算法](https://github.com/ddddxxx/LyricsKit/blob/master/Sources/LyricsService/Lyrics%2BQuality.swift)为每个歌词评分，默认选择分最高的一个。逐字时轴和翻译会为歌词额外加分。

目前暂不考虑更改选择歌词的逻辑，但欢迎改进歌词评分算法。如果你有好的想法可以pr，或者告诉我你的思路，我来改进。

**Comment by ABUGADAY** [comment]
> 有一个[相当简陋的算法](https://github.com/ddddxxx/LyricsKit/blob/master/Sources/LyricsService/Lyrics%2BQuality.swift)为每个歌词评分，默认选择分最高的一个。逐字时轴和翻译会为歌词额外加分。
> 
> 目前暂不考虑更改选择歌词的逻辑，但欢迎改进歌词评分算法。如果你有好的想法可以pr，或者告诉我你的思路，我来改进。

感谢您的回复，由于我听歌的范围比较小，所以只是根据我平时看到的结果提出一个意见，待我花点时间扩大曲目种类，学习一下swift再来看看能否优化😄
