### ISSUE TITLE
无法读取插播的音乐

### ISSUE THREAD

**Issue by hh0592821** [ddddxxx/LyricsX#308]
在音乐APP临时插播歌曲的话，lyricsX会无法获取现在播放的歌曲信息。

**Comment by ddddxxx** [comment]
未能复现。以下两种方法均能识别

- 直接播放另一首歌
- 选中另一首歌，右键菜单中选择“插播”，当前歌曲结束时转而播放插播的歌曲

请提供更详细的描述和操作步骤

**Comment by hh0592821** [comment]
我这边也无法复现了，现在好像正常了。
