### ISSUE TITLE
Disable censored words in lyrics

### ISSUE THREAD

**Issue by ShantanuNair** [ddddxxx/LyricsX#309]
I listen to a lot of hip-hop. Like 50% of any of the songs' lyrics contains "*****" in place of swear words. How do I disable this if possible?

**Comment by ddddxxx** [comment]
LyricsX have nothing to do with censoring. The lyrics source provides censored lyrics and I can't "decensor" them.

LyricsX do filter out noises in lyrics. You can config or turn it off in `Preferences -> Filter`.
