### ISSUE TITLE
Support for Cog player

### ISSUE THREAD

**Issue by ww7** [ddddxxx/LyricsX#310]
Old-school directory based music player [Cog](https://kode54.net/cog) is alive.
Can you add LyricsX support?
It's push current play to Notification center.
![](https://i.imgur.com/xMDzmOY.png)

**Comment by ddddxxx** [comment]
The NOW PLAYING widget use private magic to get playback information. Only Apple can do this. Instead, LyricsX communicate with players via AppleScript. Cog do support AppleScript, and this is all I can get:

```
{length:237.533333333333, artist:missing value, track:1, title:"01 Lycanthrope.m4a", year:0, album:missing value, bitrate:0, genre:missing value, class:playlistentry}
```

As you see, The information is extremely limited. The artist is missing. The title is basically file name and may not represent real name of the track. The most important, playback time is missing.

Cog does't post `DistributedNotification` either. Other players send message for events like play, pause, and track change, so I don't need to query via AppleScript periodically, which is inefficient.

I can add support for Cog if these issue is addressed.

**Comment by kode54** [comment]
And that would require me to write a scripting interface, and I already have no idea how to do that.

**Comment by ddddxxx** [comment]
@kode54 A notification is sufficient:

```objc
NSNotificationName name = @"kode54.cog.playerInfo";
NSDictionary *info = @{
    @"Player State": @"Playing",
    @"Player Position": @(42.0),
    @"Title": @"Shooting Stars",
    ...
};
[NSDistributedNotificationCenter.defaultCenter postNotificationName:name object:nil userInfo:info];
```

Send it whenever player info is changed.

You can even accept external control:

```objc
[NSDistributedNotificationCenter.defaultCenter addObserver:self selector:@selector(externalPlaybackControl) name:@"kode54.cog.playbackControl" object:nil];

- (void)externalPlaybackControl:(NSNotification *)notification {
    NSString *instruction = notification.userInfo[@"Instruction"];
    if ([instruction isEqualToString:@"PlayPause"]) {
        // play pause
    }
    ...
}
```

**Comment by kode54** [comment]
I’ve been doing this for nearly five years now:

https://bitbucket.org/losnoco/cog/annotate/master/Application/PlaybackEventController.m?at=master&fileviewer=file-view-default

Any way I can improve this interface is welcome.

**Comment by ddddxxx** [comment]
@kode54 Great! I noticed you use exact the same notification name as iTunes. It's wrong IMO. I can't distinguish between Cog and iTunes. It will break may application's iTunes integration including LyricsX.

Current playback time is required for LyricsX. We can add `Position` directly into userInfo, or extend `Player State` like this:
```
{"Player State": {"State": "Stopped"}}
{"Player State": {"State": "Playing", "Start Time": "1574156611.04"}}
{"Player State": {"State": "Paused", "Position": "123.45"}}
```

I'm not familiar with scriptable application either, though I believe the scripting interface is defined [here](https://bitbucket.org/losnoco/cog/src/b6ed264b3202/Cog.scriptTerminology?at=master) and `currentEntry` is invoked [here](https://bitbucket.org/losnoco/cog/src/b6ed264b3202990a5ff46fea23315beee264c6f0/Application/AppController.m#lines-114). Before scripting interface get polished, we can stick with notification interface.

**Comment by ddddxxx** [comment]
LyricsX can now read player info from the NOW PLAYING widget. See [release note](https://github.com/ddddxxx/LyricsX/releases/tag/v1.5.2).
