### ISSUE TITLE
歌词普遍慢0.5s

### ISSUE THREAD

**Issue by marsxxl** [ddddxxx/LyricsX#314]
系统：macOS 10.15.1 （19B88） 正式版
Lyrics X 版本：1.5.1 （2157）
软件：iTunes
是否可以增加修改歌词延迟与提前的功能呢

**Comment by ddddxxx** [comment]
状态栏的下拉菜单中可以调节歌词偏移，正数提前，负数延后。偏好设置中也可以设置全局歌词偏移。

**Comment by marsxxl** [comment]
这个歌词偏移我试过，貌似只会调整菜单栏位置左右平移，没发现会调整时间

**Comment by ddddxxx** [comment]
这个歌词偏移的唯一作用就是调整时间偏移。你可以通过歌词文件来确认：调整偏移后选择“歌词 -> 在 Finder 中显示”，歌词文件开头几行会加入 [offset:200] 这样的元数据。

**Comment by marsxxl** [comment]
thx
