### ISSUE TITLE
Lyrics Search option disappeared

### ISSUE THREAD

**Issue by Quorum75** [ddddxxx/LyricsX#317]
Hi.

Is it normal that the Lyrics search option disappeared?

Thanks
Bruno

**Comment by ddddxxx** [comment]
You are misidentified as App Store reviewer. Please run following script:

```
$ defaults write ddddxxx.LyricsX isInMASReview 0
```

**Comment by Quorum75** [comment]
@ddddxxx What is that script for?

**Comment by ddddxxx** [comment]
Disable "review mode" for LyricsX. It should be disabled automatically when you open LyricsX with internet connection.

This mechanism only exist in App Store version. you can also download from [GitHub Releases](https://github.com/ddddxxx/LyricsX/releases).

**Comment by Quorum75** [comment]
Are you saying by disabling it or installing the GitHub will solve the problem?

I did not find the GitHub version. Can you please provide the direct link? Thanks

**Comment by ddddxxx** [comment]
Yes. Direct link: https://github.com/ddddxxx/LyricsX/releases/download/v1.5.2-beta.1/LyricsX_1.5.2-beta.1+2213.zip

**Comment by Quorum75** [comment]
Thank you

**Comment by Quorum75** [comment]
BTW when you choose "Show Lyrics Window" (Beta version" the application crashes.
