### ISSUE TITLE
Show Lyrics Window crashes the application

### ISSUE THREAD

**Issue by Quorum75** [ddddxxx/LyricsX#319]
When you choose "Show Lyrics Window" (Beta version) the application crashes.

LyricsX 1.5.2 Beta
macOS 10.15.2 (19C57)
Apple Music Version 1.0.2.37

**Comment by zqso** [comment]
+1

**Comment by ddddxxx** [comment]
Please try [v1.5.2-beta.2](https://github.com/ddddxxx/LyricsX/releases/tag/v1.5.2-beta.2)

**Comment by zqso** [comment]
> Please try [v1.5.2-beta.2](https://github.com/ddddxxx/LyricsX/releases/tag/v1.5.2-beta.2)

Thanks. It works now.

**Comment by Quorum75** [comment]
Yes, it does not scratch anymore.
