### ISSUE TITLE
Support for IINA player

### ISSUE THREAD

**Issue by nicolas-raoul** [ddddxxx/LyricsX#320]
IINA is an open source video player, it is great for music videos and even has a "Music Mode".

The developers of IINA have not shown much interest in [adding lyrics support](https://github.com/iina/iina/issues/1138). Only movie subtitles are available.

It would be great if LyricsX could support IINA, forming a 100% open source solution :-)

**Comment by ddddxxx** [comment]
see https://github.com/ddddxxx/LyricsX/issues/330#issuecomment-601100437
