### ISSUE TITLE
Feature Request: Amazon Music

### ISSUE THREAD

**Issue by mikedvzo** [ddddxxx/LyricsX#330]
Amazon Music HD leaves the other services in the dust.  Would love to have LyricsX for Amazon Music.  I am dumping Spotify after piloting Amazon Music and finding tons of music in Ultra HD.  I will gladly donate if you can make this happen.

**Comment by ddddxxx** [comment]
v1.5.2 now support system-wide now playing application. Please enable "Use system wide now playing application" from lab, and select "Auto" for preferred music player. It should work for any player that shows playback state on system Now Playing widget.

**Comment by mikedvzo** [comment]
Thanks for the effort but unfortunately it appears as if Amazon Music is not compatible with the System Wide Now Playing Widget.  I will raise a case with Amazon but not sure were I will get with that.

**Comment by ddddxxx** [comment]
It seems Amazon Music doesn't support AppleScript either, which means I can't get music info from it.

Added Amazon Music to [unsupported players list](https://github.com/ddddxxx/LyricsX/wiki/FAQs#q-我希望支持别的播放器).
