### ISSUE TITLE
项目为何编译不起来？

### ISSUE THREAD

**Issue by chenyangxx** [ddddxxx/LyricsX#331]
非常多的 "....is only available in macOS 10.15 or newer....."

**Comment by ddddxxx** [comment]
请执行 [DevOpen](https://github.com/ddddxxx/LyricsX/blob/master/DevOpen) 以打开工程文件。

项目及其核心组件使用了 [Combine](https://developer.apple.com/documentation/combine)，并在低版本系统下使用其开源实现 [CombineX](https://github.com/cx-org/CombineX)。因此需要设置额外环境变量。详见 https://github.com/cx-org/CombineX/wiki/Combine-Compatible-Package 。

**Comment by chenyangxx** [comment]
好的，这个解决了，但是获取QQ音乐lyrics的API貌似跑不通

**Comment by chenyangxx** [comment]
GET /lyric/fcgi-bin/fcg_query_lyric_new.fcg?g_tk=5381&amp;songmid=000sU9jC3bN2dY HTTP/1.1
Host: c.y.qq.com
Referer: y.qq.com/portal/player.html
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 55ace0fe-a32d-ece0-30a2-009d4ed6365c
