### ISSUE TITLE
No lyrics anymore

### ISSUE THREAD

**Issue by Quorum75** [ddddxxx/LyricsX#336]
LyricsX 1.5.2 (2271)
macOS 10.15.2
Apple Music 1.0.2.37
Spotify 1.1.28.721.g5b5ee660

Lyrics don't show up anymore on any player.

**Comment by Quorum75** [comment]
Any response? Am I the only one facing this problem??

**Comment by ddddxxx** [comment]
Sorry for delayed response. Can you search lyrics manually?

**Comment by cv0cv0** [comment]
同样的问题。
![image](https://user-images.githubusercontent.com/18623780/77128602-a89bc280-6a8b-11ea-9803-d8efeabeea14.png)

**Comment by cv0cv0** [comment]
Suddenly it's all right again.

**Comment by cv0cv0** [comment]
Some songs can and some songs can't.

**Comment by AiryMiku** [comment]
No lyrics，the same circumstance like @cv0cv0 happened.

App Store Version 1.5.2(2270)
macOS 10.15.3
Music 1.0.3.1

![image](https://user-images.githubusercontent.com/14982480/77142419-fe3b9380-6aba-11ea-99d8-871e0997309f.png)

**Comment by Quorum75** [comment]
> Sorry for delayed response. Can you search lyrics manually?

It is impossible. The search link is greyed out. Seen snapshot 

[https://ibb.co/0DCPNrQ](url)

**Comment by ddddxxx** [comment]
@Quorum75 It means LyricsX can’t find the music you played. I personally don’t use Spotify, and it’s hard to debug Spotify due to inaccessibility of Spotify service in mainland China.
I’ll look into it anyway. Thanks for your feedback.

**Comment by Quorum75** [comment]
> @Quorum75 It means LyricsX can’t find the music you played. I personally don’t use Spotify, and it’s hard to debug Spotify due to inaccessibility of Spotify service in mainland China.
> I’ll look into it anyway. Thanks for your feedback.

If so why do you offer Spotify in the Preferences? Did I miss something?

**Comment by cv0cv0** [comment]
@Quorum75 The author may mean that Spotify has not been adequately tested.

**Comment by hellomduo** [comment]
LyricsX MAS 1.5.2 (2270)
macOS 10.15.3
音乐 1.0.3.1
使用 Apple Music

发现已添加的音乐 (在最近添加) 播放可以获取播放信息显示歌词，在 Apple Music 的浏览中播放音乐无法获取播放信息显示歌词。

视频截图:
https://www.icloud.com/iclouddrive/0J1tVNLWefAEUeotAqCeTpWmQ

**Comment by RobFog** [comment]
Same issue here after updating to 1.5.2, also with Spotify. Lyrics don't show up, manual search is greyed out.

**Comment by luras-oil** [comment]
Also find no lyrics display in Browse but in Library -> Recently Added. (iTunes)

**Comment by eivx** [comment]
I encountered the same problem,The songs played by spotify don't seem to be properly recognized by LyricsX,The lyrics search interface is blank and you can't see anything

**Comment by eivx** [comment]
Usually re-selecting the music playback software option in the settings can temporarily solve this problem

**Comment by NathanAP** [comment]
Same here for about a month now. I've tried everything in this post but none made lyrics be shown again for me.

**Comment by Quorum75** [comment]
Any news non this bug?

**Comment by NathanAP** [comment]
Update for my situation: after an update my Mac had to make, it came back to normal. I don't know why, but it was the update that made it normal again.
