### ISSUE TITLE
希望能加入foobar2000的支持

### ISSUE THREAD

**Issue by ghGYR** [ddddxxx/LyricsX#341]
foobar2000 for Mac 应该是最好的Mac hifi播放器了，希望能加入foobar2000的支持!

**Comment by ddddxxx** [comment]
请使用系统级的正在播放应用（需要 v1.5.2 测试版）。

原生支持无法实现。见[FAQ](https://github.com/ddddxxx/LyricsX/wiki/FAQs#q-我希望支持别的播放器).

**Comment by ghGYR** [comment]
> foobar2000 for Mac 应该是最好的Mac hifi播放器了，希望能加入foobar2000的支持!



> 请使用系统级的正在播放应用（需要 v1.5.2 测试版）。
> 
> 原生支持无法实现。见[FAQ](https://github.com/ddddxxx/LyricsX/wiki/FAQs#q-%E6%88%91%E5%B8%8C%E6%9C%9B%E6%94%AF%E6%8C%81%E5%88%AB%E7%9A%84%E6%92%AD%E6%94%BE%E5%99%A8).



> 请使用系统级的正在播放应用（需要 v1.5.2 测试版）。
> 
> 原生支持无法实现。见[FAQ](https://github.com/ddddxxx/LyricsX/wiki/FAQs#q-%E6%88%91%E5%B8%8C%E6%9C%9B%E6%94%AF%E6%8C%81%E5%88%AB%E7%9A%84%E6%92%AD%E6%94%BE%E5%99%A8).

好吧
