### ISSUE TITLE
不能自动下载歌词了？必须点菜单里在finder显示，才有歌词文件

### ISSUE THREAD

**Issue by chinshiro** [ddddxxx/LyricsX#342]
不能自动下载歌词了？必须点菜单里在finder显示，才有歌词文件？能否自动下载到目录。
歌词保存的文件名能否自主设置成 歌手 - 歌名形式，或者保持与歌曲文件名相同。

**Comment by ddddxxx** [comment]
歌词只会在切歌时写入文件，否则调整歌词偏移会导致频繁写入。点击“在Finder中显示”会触发一次强制写入。
有计划加入自定义歌词文件的读写位置以及文件名的功能。请耐心等待。

**Comment by chinshiro** [comment]
👍 👍👍
