### ISSUE TITLE
Auto quit with music player is not working

### ISSUE THREAD

**Issue by pilisir** [ddddxxx/LyricsX#344]
Auto Lanuch works perfect, but Quit not.
My music player is Spotify(`1.1.28.721.g5b5ee660`)
and Lyrics' version is `1.5.2` from Apple Store, just updated today and immediately found this problem.

macOS 10.15.3
I also tried after reboot, still have it.

**Comment by cristiean** [comment]
Exactly the same here

**Comment by ddddxxx** [comment]
Fixed in v1.5.4.

**Comment by pilisir** [comment]
The problem is still here with spotify in v1.5.4.

**Comment by ddddxxx** [comment]
Sorry I closed wrong issue. This should be fixed in the next release.

**Comment by Cinnabargin** [comment]
Same issue here.

**Comment by pilisir** [comment]
wonderful works
App Store Version 1.5.6（2321）good now
