### ISSUE TITLE
Help - How do i add lyric files and disable the explicit filter

### ISSUE THREAD

**Issue by nmarchantportafina** [ddddxxx/LyricsX#345]
Hi,

I hope you can help me. I love this product :)

How would i add lyric files for songs your software can't find? I looked at the sources your software pulls from but it's all in chinese so i don't understand. Also is there a way to stop swear words being filtered. I can't see the option in the preferences.

Also do you have a paypal donation link :)

**Comment by ddddxxx** [comment]
Sorry for delayed response. LyricsX doesn't filter swear words, the lyrics sources do however. See #309.
