### ISSUE TITLE
不会随着Apple Music一起关闭

### ISSUE THREAD

**Issue by dingyx99** [ddddxxx/LyricsX#346]
关闭Apple Music的时候，LyricsX不会关闭，而是将已经关闭的Music应用重新拉起，除非手动关闭LyricsX。

版本：1.5.2(2271)

**Comment by hellomduo** [comment]
LyricsX MAS 1.5.2 (2270)
macOS 10.15.3
音乐 1.0.3.1
使用 Apple Music

是的，遇到了相同的问题。在 LyricsX 开启时退出音乐 app，音乐 app会在推出后被重新启动。

**Comment by gtlions** [comment]
同样问题
商店下载安装的
macOS 10.14.6
iTunes 12.9.5.5

**Comment by lvhe19880210** [comment]
同样问题
LyricsX MAS 1.5.2 (2270)
macOS 10.15.4
音乐 1.0.4.104

**Comment by evilhentaro** [comment]
同样问题
LyricsX MAS 1.5.2 (2270)
macOS 10.15.4
音乐 1.0.4.104

**Comment by BaoliangLiu** [comment]
同样问题
macOS 10.15.4
App Store Version 1.5.3(2272)
Apple Music 1.0.4.104

尝试过重新安装git上的和App Store里的，都不行

**Comment by kai2ou** [comment]
这个问题解决了吗？

**Comment by ddddxxx** [comment]
已在 [v1.5.4](https://github.com/ddddxxx/LyricsX/releases/tag/v1.5.4) 修复。
