### ISSUE TITLE
Audirvana+3.5.30不支持，打开LyricsX后闪退

### ISSUE THREAD

**Issue by UnrealIce** [ddddxxx/LyricsX#347]
Audirvana+ 3.5.30 (3560)
LyricsX 1.5.2 (2271)
macOS Catalina 10.15.3

现象之一：
1、打开Audirvana+
2、打开LyricsX
3、放歌，LyricsX闪退

现象之二：
1、打开Audirvana+
2、放歌
3、打开LyricsX，打不开，估计是一打开就闪退了

麻烦看看怎么修复～谢啦～

**Comment by zackhy** [comment]
遇到一样的问题，希望作者可以修复～感谢！

**Comment by MagicLentil** [comment]
Same issue.

**Comment by asseywang** [comment]
+1

**Comment by ddddxxx** [comment]
已确认 [Audirvana 的 Apple Script 接口类型标注错误](https://github.com/ddddxxx/MusicPlayer/pull/3/files/59d42fdec99146fb5c9bd50a92f219e32cfec80c#diff-7561fc8059f8ff939798741b15d131ecL82)。重构时直接使用了标注的类型导致类型不匹配。

已修复，将在下一版发布。在此之前建议回退到 1.5.1 版本。
