### ISSUE TITLE
cannt open lycicsX

### ISSUE THREAD

**Issue by salithfish** [ddddxxx/LyricsX#348]
click DevOpen  show message :No matching processes belonging to you were found
macos：10.15.2

**Comment by ddddxxx** [comment]
Did you download the zip file of source code? DevOpen is used for development. You should download the application from [releases page](https://github.com/ddddxxx/LyricsX/releases).

**Comment by salithfish** [comment]
🐂🍺

 原始邮件 
发件人: ddddxxx<notifications@github.com>
收件人: ddddxxx/LyricsX<LyricsX@noreply.github.com>
抄送: salithfish<18790258213@163.com>; Author<author@noreply.github.com>
发送时间: 2020年3月26日(周四) 16:22
主题: Re: [ddddxxx/LyricsX] cannt open lycicsX (#348)


Did you download the zip file of source code? DevOpen is used for development. You should download the application from releases page.
