### ISSUE TITLE
audirvana+ 3.5.33 无法启动lyricsX 1.5.2-2271

### ISSUE THREAD

**Issue by asukahan** [ddddxxx/LyricsX#350]
audirvana+开启的情况下无法开启LyricsX，只有audirvana关了的情况下才能打开LyricsX。提早打开LyricsX再打开audirvana+也会导致LyricsX闪退。

**Comment by MagicLentil** [comment]
Same issues.

**Comment by asseywang** [comment]
+1

**Comment by ddddxxx** [comment]
Duplicate of #347
