### ISSUE TITLE
 无法为 Apple Music 显示歌词

### ISSUE THREAD

**Issue by expelliarmus2027** [ddddxxx/LyricsX#351]
我今天在github和app store上都尝试下载了lyricsX，但是始终不能显示apple music的歌词。我尝试了把prefered music player设置成auto或者单独选择iTunes，但都显示不出来apple music的歌词。但是Spotify的歌词可以正常显示。请问我可以怎样解决这个问题呢？

**Comment by expelliarmus2027** [comment]
我后来尝试升级到了mac 10.15.4，问题还是没能解决。开发者辛苦了

**Comment by salithfish** [comment]
为什么我下载之后，都没法打开呢

**Comment by ddddxxx** [comment]
有用户报告Apple Music无法识别流媒体。在修复之前，你可以在lab里打开system now playing application，并将播放器设为auto。这样可以让LyricsX从Now Playing widget里读取播放信息。

**Comment by expelliarmus2027** [comment]
> 有用户报告Apple Music无法识别流媒体。在修复之前，你可以在lab里打开system now playing application，并将播放器设为auto。这样可以让LyricsX从Now Playing widget里读取播放信息。

谢谢您，问题已解决。

**Comment by 51164500109** [comment]
> 有用户报告Apple Music无法识别流媒体。在修复之前，你可以在lab里打开system now playing application，并将播放器设为auto。这样可以让LyricsX从Now Playing widget里读取播放信息。

不work！

**Comment by ddddxxx** [comment]
1.5.3已修复Apple Music流媒体问题，请将首选播放器切回iTunes试试？

**Comment by gth7754125** [comment]
The problem has been solved when update to 1.5.4.
