### ISSUE TITLE
打开为iTunes自动写入歌词后，会覆盖之前有歌词的歌曲，并且原来毛玻璃特效没有了。

### ISSUE THREAD

**Issue by MarkRushB** [ddddxxx/LyricsX#357]
这个问题请问如何解决呢？

**Comment by ddddxxx** [comment]
无法解决。写入歌词时并没有“覆盖”任何歌词，iTunes提供的歌词是附加的。一旦歌曲文件中包含了歌词，iTunes就不会为此歌曲提供歌词。第三方应用也无法查询iTunes是否为某首歌提供歌词。
