### ISSUE TITLE
 Donate QR code Leads to "address invalid"

### ISSUE THREAD

**Issue by leland359** [ddddxxx/LyricsX#363]
I want to donate to the project but the link leads to "address invalid" and has what I think is Chinese (?) writing on it. What I did was press the "Donate.." button in the menu and then a window popped up and I scanned the QR code w/ my phone. The site also comes up as invalid address on my laptop.

**Comment by Pazakui1259** [comment]
That QR code is from Alipay - a Chinese payment app - and it's supposed to be scan using only the Alipay app. I don't think a non-Chinese citizen can easily using Alipay.

**Comment by leland359** [comment]
Is there a Patreon I can donate to?

**Comment by Pazakui1259** [comment]
> Is there a Patreon I can donate to?
> […](#)

I didn't seem to find any Patreon. You might have to contact the original author @ddddxxx .

**Comment by ddddxxx** [comment]
Hi, currently Alipay is the only way to donate. Please feel free using LyricsX freely. This project is driven by love, not crowdfunding.

You can also support LyricsX by:
- Tell other people about LyricsX
- Rate / write comment in Mac App Store
- Report bugs and make feature request
- Stay home and be safe 😉
