### ISSUE TITLE
Sonos support

### ISSUE THREAD

**Issue by rolszowy** [ddddxxx/LyricsX#365]
When I use Spotify Connect with Sonos speakers, LyricsX 1.5.2(2271) doesn't show the lyrics. I've tested it also with other Spotify Connect devices like Amazon Echo and no effect. LyricsX works when I play it directly on my mac. AirPlay works, but it's understandable as it's just streaming audio directly to the speakers. Are you planning to support this?

**Comment by ddddxxx** [comment]
It's Spotify's issue. see #312
