### ISSUE TITLE
Feature Request: 分别定义歌词和译文的字号大小

### ISSUE THREAD

**Issue by cuteday** [ddddxxx/LyricsX#368]
如题，在逐行模式使用双语模式时，支持将原文和翻译的大小区别显示，可能会有比较美观的视觉/强调效果。
另一个可能的feature：选择歌词时，支持自定义来源的优先级。

非常实用的软件！感谢创作者^ ^

**Comment by ddddxxx** [comment]
很抱歉一直没有回复。由于当前的架构，这个功能需要相当的工作量，应该不会考虑了。

以前曾经有过歌词源优先的选项，由于效果不好而改成了现在的歌词评分算法，不会考虑加回来。
