### ISSUE TITLE
LyricsX prevent Apple Music from quiting

### ISSUE THREAD

**Issue by J-Siu** [ddddxxx/LyricsX#370]
LyricsX 1.5.2 from app store
MacOS 10.15.4

I am not sure when this start.

In the past, when I open Apple Music, LyricsX will auto launch, and when I quit Apple Music, LyricsX will quit together.

Now, when I open Apple Music, LyricsX will auto launch, and when I quit Apple Music, it will not quit, just minimized to the dock. I have to quit LyricsX manually first, then quit Apple Music.

**Comment by DriedYellowPeach** [comment]
that is true, I found this problem too.

**Comment by cv0cv0** [comment]
some

**Comment by ddddxxx** [comment]
Fixed in [v1.5.4](https://github.com/ddddxxx/LyricsX/releases/tag/v1.5.4).

**Comment by J-Siu** [comment]
Confirm Apple Music is no longer block from close. LyricsX remain running.

Is LyricsX suppose to close or stay when closing Music? I am ok with either. Just want to make sure it is not a silent bug.

**Comment by ddddxxx** [comment]
Auto quit with player is not fixed yet as it's less annoying. I'm still working on it.

**Comment by ddddxxx** [comment]
Auto quit issue is tracked at #344. close this.
