### ISSUE TITLE
App store version preference "Lab" tab error

### ISSUE THREAD

**Issue by J-Siu** [ddddxxx/LyricsX#371]
LyricsX 1.5.2 from app store
MacOS 10.15.4

1. Preference -> Lab, "Enable Touch Bar lyrics" is enabled by default

![Screen Shot 2020-04-25 at 2 55 10 PM](https://user-images.githubusercontent.com/3171920/80288432-e385bb80-8705-11ea-98ab-d309ab65e9c8.png)

2. Remove check mark. error pop-up "Unable to to enable Touch Bar lyrics" ...

![Screen Shot 2020-04-25 at 2 54 48 PM](https://user-images.githubusercontent.com/3171920/80288438-eaacc980-8705-11ea-87da-4899656483e1.png)

3. Close Preference and open again, go to Lab, "Enable Touch Bar lyrics" check mark is again there.

**Comment by ddddxxx** [comment]
Confirmed It's a UI issue. The default state of the button is incorrect and does not reflect the state of Touch Bar lyrics.
