### ISSUE TITLE
It wont open

### ISSUE THREAD

**Issue by ambwng** [ddddxxx/LyricsX#374]
When I launched the app nothing happened and now when I'm trying to delete it it says "can't move to the bin because it is open"?

**Comment by ddddxxx** [comment]
LyricsX lives in your menu bar:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/11691433/80950416-6276a480-8e28-11ea-8b00-6621a5731ca5.png">

**Comment by ddddxxx** [comment]
close due to inactivity
