### ISSUE TITLE
I think there's a typo on the English `maching` which should be `matching`

### ISSUE THREAD

**Issue by leocaseiro** [ddddxxx/LyricsX#376]
Hi, while translation from English to Portuguese, I realized that it might have a small typo with the work **matching** which is missing the **T** in the file.

Mach is a number, and I think you meant matching.

> [Lyrics lines matching following rules will be ignored. Use \"/\" to start a regular expression.](https://github.com/ddddxxx/LyricsX/blob/master/LyricsX/en.lproj/Preferences.strings#L8)

I'm happy to push a PR if you agree it's a typo. Otherwise, please ignore this issue.

Cheers.

**Comment by ddddxxx** [comment]
Thank you. A PR is welcome!
