### ISSUE TITLE
希望可以支持Tidal！！！！！！

### ISSUE THREAD

**Issue by MagicLentil** [ddddxxx/LyricsX#377]
拜托！！！！

**Comment by ddddxxx** [comment]
TIDAL 并不支持 AppleScript，[已更新FAQ](https://github.com/ddddxxx/LyricsX/wiki/FAQs#q-我希望支持别的播放器)。

可通过通知中心的"播放中"读取歌曲信息，请前往"偏好设置" -> "实验室"，勾选"Use system wide now playing application"，并将首选音乐播放器设为"自动选择"。
