### ISSUE TITLE
Some lyrics are wrong

### ISSUE THREAD

**Issue by leon47331** [ddddxxx/LyricsX#383]
Some lyrics are wrong and does not fit with the song at all.

**Comment by ddddxxx** [comment]
You can search lyrics manually or click `Lyrics` -> `Wrong Lyrics` to remove the wrong one.

**Comment by leon47331** [comment]
But there are typos or wrong words and then it is useless to delete the whole lyric.

**Comment by ddddxxx** [comment]
You can edit the lyrics file yourself. Click `Lyrics` -> `Show In Finder`.

**Comment by leon47331** [comment]
I already tried this but it is still showing the wrong lyric.

**Comment by ddddxxx** [comment]
Restart LyricsX so it can load the latest version from disk.

**Comment by ddddxxx** [comment]
Note LyricsX is not a lyrics service provider like Musixmatch. It's just a tool which "auto search and download lyrics **from the internet**, and displays them". LyricsX does't own these lyrics. You can't upload lyrics or report wrong lyrics because LyricsX doesn't have a centralized server. When you click "Wrong Lyrics", LyricsX merely remove it from your disk.

**Comment by leon47331** [comment]
> Restart LyricsX so it can load the latest version from disk.

This works!



> Note LyricsX is not a lyrics service provider like Musixmatch. It's just a tool which "auto search and download lyrics **from the internet**, and displays them". LyricsX does't own these lyrics. You can't upload lyrics or report wrong lyrics because LyricsX doesn't have a centralized server. When you click "Wrong Lyrics", LyricsX merely remove it from your disk.

I understand this but then the lyrics that LyricsX is using (or downloading) are wrong.
This is not your fault, but the fault of the platform which is providing the lyrics.

**Comment by ddddxxx** [comment]
You probably want to enable "Strict Search" in preferences. It prevent LyricsX from loading obviously wrong lyrics.
