### ISSUE TITLE
No such module 'CombineX'

### ISSUE THREAD

**Issue by JCsplash** [ddddxxx/LyricsX#389]
Also getting no module for 'SnapKit' 'GenericID', 'DFRPrivate', 'MASShortcut', and 'Sparkle' - when building the project.

<img width="1384" alt="Screen Shot 2020-06-03 at 10 54 01 PM" src="https://user-images.githubusercontent.com/16738930/83710127-fe452d00-a5ed-11ea-9437-202b35f8c613.png">

@ddddxxx  Any ideas how to fix this?

**Comment by JCsplash** [comment]
Just installed Carthage packages and resolved all errors except for the CombineX one.

**Comment by ddddxxx** [comment]
CombineX has compatibility issue with Xcode 11.4+. Currently I'm using Xcode 11.3.1 to build LyricsX.

**Comment by JCsplash** [comment]
@ddddxxx  No worries, i ended up just using Combine instead of CombineX. Love the library thank you! A few others questions if you have some time:

1. Is there a way to import LRC files from outside of LyricsX? I’d love to be able to trigger draggedFinished or the importLyrics function from a shell script if possible.

2. Do both UserDefaults (wrong lyrics) and Saved LRC Files (in the music folder) persist even when the app is deleted? So far they seem like they do but wanted to double check.

**Comment by ddddxxx** [comment]
1. No. I'd like to add it, please file an issue.
2. Neither of them is removed when you delete the app.

**Comment by ddddxxx** [comment]
Fixed in cx-org/CombineX#81. CombineX 0.2.1 now works with Xcode 11.4+.

**Comment by JCsplash** [comment]
@ddddxxx Thanks for the bug fix! Apologies for the late reply. I ended up writing a simple command line utility to save lyrics as lrcx files in the Music folder and it works great. Thank you again for the great library!
