### ISSUE TITLE
歌词不能滚动，重启变正常

### ISSUE THREAD

**Issue by kurt2715** [ddddxxx/LyricsX#393]
macos， version：1.5.4
很多时候，歌词会忽然变得不能滚动。
重启lyricsX，歌词会变得正常能滚动。
不定期能复现该问题。

**Comment by kurt2715** [comment]
补充：
复现过程应该是，
本来正常滚动，如果手动滚动过歌词，歌词就变得不能再自动滚动了。

**Comment by ddddxxx** [comment]
点击左下角的按钮以继续滚动。也可点击空格键。

**Comment by kurt2715** [comment]
原来是我的使用问题，多谢~
