### ISSUE TITLE
Chinese translation is not working

### ISSUE THREAD

**Issue by yip924** [ddddxxx/LyricsX#395]
The Kanji in Japanese lyrics becomes simplified, even though I have switched on the auto translation to Traditional Chinese. 
<img width="507" alt="螢幕截圖 2020-06-23 下午9 37 56" src="https://user-images.githubusercontent.com/30944695/85410581-d9fbc100-b599-11ea-9c9b-28c4642350fd.png">

**Comment by ddddxxx** [comment]
This function is named "Auto Chinese conversion". It only convert Chinese lyrics, as its name suggested. Conversion on Japanese lyrics is deliberately disabled.

**Comment by yip924** [comment]
Oh I see, that makes sense.
Does that mean the source lyrics was already mistakenly translated into simplified? Is there any way to avoid it other than manually changing the lyrics file?

**Comment by ddddxxx** [comment]
I think so. Most lyrics sources are music service provider in mainland China. LyricsX don't fix their problem. and I don't think performing Chinese Conversion on Japanese lyrics is a good idea.
