### ISSUE TITLE
Itunes lyrics changed in iPhone

### ISSUE THREAD

**Issue by morzahavi** [ddddxxx/LyricsX#403]
Hi,
I use LyricsX and enjoy it. I have recently discovered that the lyrics I have applied in iTunes on my Mac are synced with my phone. Is it possible to apply the lyrics so that I will only see them in the LyricsX window?

**Comment by ddddxxx** [comment]
LyricsX won't sync lyrics to iTunes unless you enabled `Preferences -> Lab -> Write lyrics to iTunes -> Automatically`, or do it manually from `Main Menu -> Lyrics -> Write to iTunes`.
