### ISSUE TITLE
支持的歌词文件格式

### ISSUE THREAD

**Issue by leranjun** [ddddxxx/LyricsX#411]
想请问一下，当前除了标准lrc以及lrcx文件以外，还有其他支持的格式吗？

有一些歌曲无法搜寻到逐字歌词，看到 #222 提到的enhanced lrc format暂时还没有支持，一些播放器特定的歌词格式（trc、krc、qrc之类）又很难解析。

（什么时候lrcx格式有编辑器就好了XD）

**Comment by ddddxxx** [comment]
实际上 LyricsKit 是可以[解析 krc 和 xtrc 等格式](https://github.com/ddddxxx/LyricsKit/blob/master/Sources/LyricsService/Parser/KugouKrcParser.swift)的（因为相应的歌词源只提供这样的歌词）。但应用层面只提供了导入 lrcx 的功能。因为 lrcx 是 lrc 的超集，所以你也可以将普通 lrc 作为 lrcx 来导入。

这些功能，包括 enhanced lrc 都没有技术上的困难。但是个人的时间和精力实在有限……
