### ISSUE TITLE
Feature to add own lyrics

### ISSUE THREAD

**Issue by RychEmrycho** [ddddxxx/LyricsX#422]
I found a lot of songs that have not been backed up (mostly local songs). I think it would be nice if we could add our own lyrics (because actually we can find the lyrics just by googling it but it would be very troublesome if we are working with many tabs/windows on our screen). 
In essence, if the lyrics are not found from online sources, we can choose the option to add lyrics to the song, for storage it is okay to be on our local computer.

**Comment by nerdybo** [comment]
Second that!

**Comment by LuCa-0** [comment]
There already is a feature for that! You just have to toggle "Show Lyrics Window" and then you can drag and drop the .lrc file in there and it will be imported into LyricsX 😄

**Comment by RychEmrycho** [comment]
thanks @LuCa-0 , I didn't know this feature already existed
