### ISSUE TITLE
Draggable crashes LyricsX in 1.5.5

### ISSUE THREAD

**Issue by LightFocus** [ddddxxx/LyricsX#423]
Version 1.5.5
When select "Draggable" and unselect "Disable lyrics when Mouse passing by"
And try to drag the lyrics area would crash the App

**Comment by luckman212** [comment]
Same problem here

Actually a lot of things crash 1.5.5... for me it also crashes when switching through various tabs in the Preferences.

**Comment by ddddxxx** [comment]
Thanks for detailed information. I just identified the problem and will fix asap.
