### ISSUE TITLE
App doesn't open

### ISSUE THREAD

**Issue by vituxre** [ddddxxx/LyricsX#424]
App doesn't open at all just flashes when trying to open
app version 1.5.5
mac os catalina 10.15.7

**Comment by asiaryckobozenska** [comment]
+1

Freshly installed from the App Store. macOS 10.15.7

**Comment by Daleindeed** [comment]
Yes. I am having the same problem :(

**Comment by ddddxxx** [comment]
v1.5.6 should fix this.

**Comment by vituxre** [comment]
Thanks works great now :)
