### ISSUE TITLE
下载了源码怎么启动啊

### ISSUE THREAD

**Issue by GitHub-fengyanwei** [ddddxxx/LyricsX#441]
下载了源码怎么启动啊

**Comment by ddddxxx** [comment]
如果只是运行程序，请在 [releases](https://github.com/ddddxxx/LyricsX/releases) 下载程序包。[这是 v1.5.6 版的直链](https://github.com/ddddxxx/LyricsX/releases/download/v1.5.6/LyricsX_1.5.6+2322.zip)。如果要编译的话请执行[DevOpen](https://github.com/ddddxxx/LyricsX/blob/master/DevOpen)
