### ISSUE TITLE
非播放列表或資料庫的歌曲不會顯示歌詞

### ISSUE THREAD

**Issue by benson1989** [ddddxxx/LyricsX#446]
11.1 Beta版（20C5061b）

LyricsX
GitHub Version 1.5.6（2322）

歌曲是從資料庫或是播放列表播(紅色框框)放的話才會有歌詞

假如是從搜尋或是藝人專輯(綠色框框)直接放 歌詞會顯示不出來

LyricsX 選單搜尋歌詞和歌詞會反灰 無法選擇
![2](https://i.imgur.com/fHEwGGL.png)

![1](https://i.imgur.com/jDHJJuO.png)

**Comment by ddddxxx** [comment]
参见 #437

**Comment by benson1989** [comment]
> 参见 #437

感謝
Safari或其他的App播放音樂或影片也會自動載入歌詞 這個未來會修改嗎?
還是需要手動假如拿兩個Code? (從來沒農過碼QQ)
