### ISSUE TITLE
Big Sur 无法搜索当前播放的电台和专辑的歌词，只有播放播放列表时才显示

### ISSUE THREAD

**Issue by 1982606762** [ddddxxx/LyricsX#460]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/46312707/104867880-db009f80-597c-11eb-960a-ea636bd0857b.png">
当前正在播放歌曲，但是不自动搜索歌词，也不能手动搜索

**Comment by wangxufire** [comment]
不是在曲库里播放的好像就这样

**Comment by hyunbinrain** [comment]
> <img alt="image" width="237" src="https://user-images.githubusercontent.com/46312707/104867880-db009f80-597c-11eb-960a-ea636bd0857b.png">
> 
> 当前正在播放歌曲，但是不自动搜索歌词，也不能手动搜索

兄弟你看看在 big sur 下，桌面歌词能否拖动到Dock旁边的空间？

**Comment by hyunbinrain** [comment]
![](https://user-images.githubusercontent.com/3376425/104113449-cdbc3300-5334-11eb-9052-766b0393940c.png)

**Comment by 1982606762** [comment]
我播放的是我歌单里的歌……而且以前Catalina版本就正常，升级bigsur后就这样了

发自我的iPhone

**Comment by 1982606762** [comment]
今天打开似乎好了。。

**Comment by 1982606762** [comment]
> > <img alt="image" width="237" src="https://user-images.githubusercontent.com/46312707/104867880-db009f80-597c-11eb-960a-ea636bd0857b.png">
> > 当前正在播放歌曲，但是不自动搜索歌词，也不能手动搜索
> 
> 兄弟你看看在 big sur 下，桌面歌词能否拖动到Dock旁边的空间？

可以
![image](https://user-images.githubusercontent.com/46312707/104975881-de586180-5a36-11eb-954d-20bf935852ab.png)

**Comment by 1982606762** [comment]
我发现当前播放自定义的播放列表里的歌曲就可以出现歌词，但是播放电台歌曲和专辑时就算歌曲已经添加进内容库也不出现歌词

**Comment by ddddxxx** [comment]
参见 #437
