### ISSUE TITLE
自制歌词

### ISSUE THREAD

**Issue by YCHX** [ddddxxx/LyricsX#465]
搜索歌词时不是严格一致得到的歌词在自行修改以后下次播放的时候会重新搜索, 导致自行修改的歌词被覆盖.
提议能否加入添加自制歌词等而非通过搜索

**Comment by MarcusJr** [comment]
自制歌词上传需要拍模板什么的吗，矫正时间轴 etc

**Comment by YCHX** [comment]
我是为了自用制作的歌词, 不太清楚上传需要什么

**Comment by YCHX** [comment]
> 搜索歌词时不是严格一致得到的歌词在自行修改以后下次播放的时候会重新搜索, 导致自行修改的歌词被覆盖.
> 提议能否加入添加自制歌词等而非通过搜索

修正: 只有少数情况会发生上述状况, 大部分歌曲在编辑歌词后都能正常读取, 但有少部分编辑后不读取并且拖拽歌词进去下次播放也仍然没有歌词

**Comment by YCHX** [comment]
> > 搜索歌词时不是严格一致得到的歌词在自行修改以后下次播放的时候会重新搜索, 导致自行修改的歌词被覆盖.
> > 提议能否加入添加自制歌词等而非通过搜索
> 
> 修正: 只有少数情况会发生上述状况, 大部分歌曲在编辑歌词后都能正常读取, 但有少部分编辑后不读取并且拖拽歌词进去下次播放也仍然没有歌词

补充: 出现问题的歌曲的演唱者都是多人, artist显示里为"XXX/XXX", 带有 半角斜杠 / 就会出现该问题

**Comment by ddddxxx** [comment]
这是个Bug。查找本地歌词的时候是按照文件名来找的，文件名里如果有`/`会找不到，然后重新搜索。

这还是HFS+的历史问题，你在Finder里看到`/`其实是`:`（`ls`能看到真实的文件名）。无论如何，LyricsX自己存的文件，自己应该能读到才行。我在写入时转换了一次，读的时候忘了转换。
