### ISSUE TITLE
当某一句歌词过长时,会导致从下一句开始,位置发生向右的移动

### ISSUE THREAD

**Issue by hidden-lii** [ddddxxx/LyricsX#473]
退出软件重新打开后会正常,过一段时间(没有具体去测试触发回归正常的条件是否为时间)会回归正常.
这应该是一个bug,如果可以的话望解决

**Comment by ddddxxx** [comment]
感谢反馈。之后的版本中，过长的歌词会从两边截断，不再影响布局区域。
