### ISSUE TITLE
Mac Monterey 12.1 Beta版(21C5021h) 网易云歌词来源失效

### ISSUE THREAD

**Issue by whoisfancy** [ddddxxx/LyricsX#527]
RT，我无法搜索出网易云来源的歌词，QQ或者kugou可以正常使用，很多网易云独占的歌有歌词但是搜不到，有试过重装软件，但是依然无法使用

**Comment by whoisfancy** [comment]
比如Hallucination-P3PPER/Milkoi/Darm这首歌；另，软件版本是GitHub版1.61（2341）

**Comment by MiracleCsf** [comment]
我的也是，只有QQ音乐源，没有163了

**Comment by BillCao1997** [comment]
存在同样的问题，不过我还在Catalina

**Comment by cogitoxin** [comment]
@BillCao1997 同Catalina，同样的issue

**Comment by Mrvica7** [comment]
12.1正式版 +1

**Comment by Pablolu430** [comment]
12.1+1
<img width="1440" alt="截圖 2021-12-29 11 01 46" src="https://user-images.githubusercontent.com/49023418/147623468-dafafa36-28a9-470b-b442-48ed8d992a28.png">
 不曉得他是不是castellano翻成español 🤣

**Comment by ddddxxx** [comment]
是网易的服务端有变动，已由 @hguandl 修复。已发布 v1.6.3 解决此问题。

**Comment by Pablolu430** [comment]
感謝大大～ 不過我現在還是有個小小小問題 就是rhythm那依舊只有摳摳音樂 😂😂😂 
求大神或是安卓端有類似的app嗎 😭😭😭
