### ISSUE TITLE
搜索歌词界面点击搜索会闪退

### ISSUE THREAD

**Issue by linbo0518** [ddddxxx/LyricsX#60]
macOS: 10.12.5
Version:  1.1.4(1190)

搜索歌词界面点击搜索会闪退。
![image](https://user-images.githubusercontent.com/5896078/27514534-63cd2aec-59c0-11e7-98ed-edcb9f91fd81.png)

**Comment by XQS6LB3A** [comment]
已确认，将在下一个版本修复。

**Comment by XQS6LB3A** [comment]
50747a5 可能可能已经修复了这个问题。
