### ISSUE TITLE
Spotify on MacOS only working for first song

### ISSUE THREAD

**Issue by bajosoto** [ddddxxx/LyricsX#618]
MacBook Pro M1 Apple Silicon
MacOS 14.1.1 
Spotify 1.2.26 

Using Spotify, I'm only able to fetch the lyrics for the first song playing. If I skip the song or it finishes, I'm unable to search for the lyrics of the next one. The manual "Search Lyrics" function is enabled, but pressing the button results in nothing found. In short, I'm only able to fetch lyrics for ONE song.

If I force quit LyricsX from the Activity Monitor and reopen it, I'm able to fetch the lyrics again, but only once.

Is there any way I can check logs to see if something in LyricsKit or LyricsX is crashing after the first search?

**Comment by Alexcyh7** [comment]
Hey, try to use the package from this #601

**Comment by bajosoto** [comment]
@Alexcyh7 Thank you! This version fixed my problems
