### ISSUE TITLE
Lyric font fallback support

### ISSUE THREAD

**Issue by syhily** [ddddxxx/LyricsX#62]
Increase the lyric font face configuration number. So the user could select a group of font. Because some font only support one language, the default font fail back could be kindle of ugly.

![image](https://user-images.githubusercontent.com/1761698/27601687-cfe554e0-5b35-11e7-93f4-7c84594817b2.png)

**Comment by ddddxxx** [comment]
Could you give me the font and LRC file in the screenshot? I (probably) have done this, but unable to test.
