### ISSUE TITLE
无法通过歌词偏移调整时间

### ISSUE THREAD

**Issue by Hastronaut** [ddddxxx/LyricsX#631]
macOS 13.2.1, LyricsX 1.6.3, 使用Spotify播放歌时经常出现显示的歌词比播放器上的慢好几句的问题。
然后尝试着使用歌词偏移工具，并查看原文件的变化，发现在相应的.lrcx文件前几行的确出现了 [offset:1500] 这样的代码，但是重新播放之后并没有起到改变歌词显示的效果，仍然和原来一样，这是什么原因呢

**Comment by aviwad** [comment]
This is because of a glitch in Spotify. When songs autoplay, Spotify induces a lag that play/pausing fixes. My app Lyric Fever (https://LyricFever.com) has fixed this glitch! But I will release a version with a fix very soon. Please check it soon :)
