### ISSUE TITLE
Spotify 播放广告时也会继续显示无关歌词

### ISSUE THREAD

**Issue by R-L-T-Y** [ddddxxx/LyricsX#72]
比较小的毛病
但是有点尴尬

**Comment by ddddxxx** [comment]
你是说 Apple Music 的广告吗？我有订阅所以没遇到过这种问题。

**Comment by R-L-T-Y** [comment]
不好意思没说清楚，是Spotify

**Comment by ddddxxx** [comment]
似乎在 Spotify 中，广告也是一个普通的音轨，有对应的信息。LyricsX 会使用这些信息来搜索歌词。

可否在 Spotify 播放广告时点击“搜索歌词”，搜索框会自动填写音轨信息。请将这些信息提供给我，我会屏蔽对此类音轨的歌词搜索。

**Comment by R-L-T-Y** [comment]
Title:Spotify
Artist:
(Blank)

点击wrong lyric之后不再出现
