### ISSUE TITLE
可以增加支持其它播放器吗

### ISSUE THREAD

**Issue by zhouchang714** [ddddxxx/LyricsX#73]
这是一个很棒的作品，非常喜欢逐行歌词的效果，但是现版本支持的几个播放器的曲库并没有国内一些音乐播放器，譬如网易云等曲库内容丰富。而同时这些播放器的桌面歌词实在是鸡肋，界面十分丑陋，望作者能增加对诸如网易云等的支持，谢谢

**Comment by ddddxxx** [comment]
技术上无法实现。跨应用采集歌曲信息需要播放器主动提供AppleScript接口，而网易云等一众国产播放器均不支持。

**Comment by ijry** [comment]
想办法hack嘛，支持国内APP就牛了。

**Comment by ddddxxx** [comment]
[v1.5.3-beta.3](https://github.com/ddddxxx/LyricsX/releases/tag/v1.5.2-beta.3) 已支持系统级的正在播放应用，包括网易云音乐。

**Comment by bmxklYzj** [comment]
> [v1.5.3-beta.3](https://github.com/ddddxxx/LyricsX/releases/tag/v1.5.2-beta.3) 已支持系统级的正在播放应用，包括网易云音乐。

太赞了。
