### ISSUE TITLE
Add more lyrics sources

### ISSUE THREAD

**Issue by tuantmtb** [ddddxxx/LyricsX#75]
When I use Musixmatch, I can find more lyrics although LyricsX can't find it.
Could you add source lyrics from Musixmatch ?
Thank you 💯

**Comment by ddddxxx** [comment]
Thanks for your advice. However, it cannot be done. Musixmatch do not support free API access, and their commercial agreement is too expensive.

**Comment by tuantmtb** [comment]
LyricsX can try other services. For example: http://mp3.zing.vn http://www.nhaccuatui.com
Thank your team <3

**Comment by ddddxxx** [comment]
@tuantmtb The services you listed above do not provide synchronized lyrics.

If you have any information about other lyrics services, please feel free to open a new issue.
