### ISSUE TITLE
桌面逐行歌词的[上,左,右]定位无效

### ISSUE THREAD

**Issue by Halomaple** [ddddxxx/LyricsX#76]
如下图所示：
- **右** 屏幕边缘的距离设为 **0** 时桌面歌词不会靠右。
- **左边** 和 **上边** 也有同样的问题。
- **下边** 与Docker的距离是工作的。
<img width="609" alt="lyricsxissue" src="https://user-images.githubusercontent.com/7535597/28498938-a557e876-6fdc-11e7-9e3b-083f40d12c6c.png">

**Comment by ddddxxx** [comment]
见[这个回复](https://github.com/ddddxxx/LyricsX/issues/37#issuecomment-304035767)
