### ISSUE TITLE
關於 Chinese Conversion 的問題

### ISSUE THREAD

**Issue by Windypper** [ddddxxx/LyricsX#77]
請問可否提供 Chinese Conversion 更詳細的設定，如 OpenCC 中的 s2t, s2tw, s2hk ？
另外，可否在使用 Chinese Conversion 後，將寫入 iTunes 的歌詞也依從其設定？

**Comment by ddddxxx** [comment]
你好
我并不打算提供 Chinese Conversion 的详细设定。这在技术上没有难度，但我希望以尽可能简洁的方式提供最核心的功能。
将简繁转换后的歌词写入 iTunes 是合理的做法，我会在将来的版本中更新。

**Comment by Windypper** [comment]
好的，我尊重您的考慮，那請問 Chinese Conversion 是否直接調用的 OpenCC 的 s2t 的 config 呢？若是的話，自行修改 s2t.json 應該沒有什麼問題吧？
另外，經過一段時間的使用之後發現，Chinese Conversion 功能並不穩定，時而有效時而無效，需要在 Preference 裡面將其關閉再打開才有效，若可以，希望針對此做一些 improvement。

**Comment by ddddxxx** [comment]
我使用的是我自己封装的 [SwiftyOpenCC](https://github.com/ddddxxx/SwiftyOpenCC)，你可能无法自行修改配置文件。
关于简繁转换失效的问题，还请新开一个issue，我将跟踪解决。
