### ISSUE TITLE
将歌词写入iTunes的时候，自动去除多余的换行符

### ISSUE THREAD

**Issue by oscar-c** [ddddxxx/LyricsX#79]
如题，版本1.1.4在写入iTunes的时候会在歌词的末尾再加上一个换行符。

**Comment by ddddxxx** [comment]
事实上这是预期中的行为。我将行尾的换行符视为行的一部分，所以歌词末尾应当有换行符。
我可以去除开头的空行，以及文件中连续的空行。这是很好的建议，非常感谢。
至于去除末尾的换行符，有更多理由吗？

**Comment by ddddxxx** [comment]
我注意到 iTunes 提供的歌词也包含末尾的换行符
<img width="523" alt="2017-07-31 23 51 06" src="https://user-images.githubusercontent.com/11691433/28786436-c82f5652-764b-11e7-9f69-72c7514d8906.png">

**Comment by oscar-c** [comment]
文件中连续的空格可能暗示着歌词的分段，如果全部去掉会影响读歌词时候的体验。
末尾的换行符会导致在歌词的显示在iOS体验上不统一
比如这是开头的样子 ![开头](https://d.pr/I8TPD2+)
而到了结尾就变成这样了![结尾](https://d.pr/xDKT5+)
注意一下结尾那边多空出了空格出来

**Comment by ddddxxx** [comment]
我想请你确认一下图中歌词的末尾有几个`<LF>`，我这里不太方便验证。

我打算：
去除开头和末尾的“空行”，即首字符不为`<LF>`，末尾仅有一个`<LF>`。
去除连续的“空行”，即不允许出现连续三个`<LF>`。

我对行的定义来自 [POSIX Standard Definitions](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).
> 3.206 Line
> A sequence of zero or more non- <newline> characters plus a terminating <newline> character.

**Comment by oscar-c** [comment]
这个要怎么验证？
我试着用`ffprobe`对写入歌词后的文件进行了查看。
`$ ffprobe 01\ 39みゅーじっく\!.m4a`
写入后是[这样的](http://d.pr/n/meLWEu+)
我可以上传这首歌曲，如果你需要的话。

**Comment by ddddxxx** [comment]
文件末尾不止一个\<LF>。应该是原歌词文件末尾就有空行。就我测试，去除额外空行之后显示效果不会很突兀。

我会在将来的版本中更新。下一个版本 1.2.0 已进入发布流程，不再添加新功能。

**Comment by oscar-c** [comment]
如果我刚才贴的输出算是“末尾不止一个<LF>“的话，我又测试了四个文件，其中三个结尾都是“末尾不止一个<LF>”，所以这个问题还是比较普遍的。

**Comment by ddddxxx** [comment]
歌词文件默认放在 `~/Music/LyricsX`，你可以查看LRC文件末尾是否是空行（仅有时间戳，内容是空的）
你还可以打开 iTunes，右键歌曲，选择“Get Info”，在歌词栏中编辑掉多余的空格，然后同步到 iPhone 上查看显示效果。

**Comment by oscar-c** [comment]
在iTunes上手动去掉空行、同步到iOS设备上之后，歌词的显示效果很好。
按你描述的去找，果然那些文件的最后是有“仅有时间戳，内容是空的”的空行。
歌词文件末尾的空行因该是为了让最后一句歌词及时消失的，但是我觉得在iTunes的歌词里面对照着也空一行就没有什么意义了。

**Comment by ddddxxx** [comment]
是这样的，我会按照[这条回复](https://github.com/ddddxxx/LyricsX/issues/79#issuecomment-319123485)的方案改进。

**Comment by oscar-c** [comment]
> 末尾有且仅有一个<LF>

我的一点猜想：歌曲的Tag Field的末尾一般是不带换行符的，因为内容就只有一“行”。这里的“行”因为不是用换行符来结尾，所以并不是严格意义上的一“行”。
歌词的内部，每行的末尾是需要换行的，但是歌词的最后，就像其它的Tag一样，应该是不需要一个换行符的。这样来看，歌词的最后一句，按照你的定义来判断的话，并不算一“行”，
我贴出来的`ffprobe`的报告里面，末尾的两个新行，其中一个是因为歌词最后有一个空行，另外一个是是最后一句非空的歌词还有一个换行。
我觉得这两个都删掉会不会更好一点？

**Comment by ddddxxx** [comment]
我们大可不必纠结定义问题，一切以最终显示效果为准。请耐心等待新版发布。
