### ISSUE TITLE
设置了随itunes启动退出，但仅可退出，启动无效

### ISSUE THREAD

**Issue by koukisakurai** [ddddxxx/LyricsX#81]
系统版本是 10.12.6
![2017-08-03 17 32 04](https://user-images.githubusercontent.com/7870396/28915430-adf797b8-7871-11e7-8312-b49752f25d0f.png)

**Comment by ddddxxx** [comment]
自动启动的功能是由一个独立的应用程序完成的，名为`LyricsXHelper`。它监视播放器的运行情况并在合适的时机启动 LyricsX。

请打开活动监视器并搜索`LyricsXHelper`，确认各种情况下的运行状况。

**Comment by koukisakurai** [comment]
@ddddxxx `LyricsXHelper` 日常并未运行在后台，启动iTunes后也并未同时启动。
需要手动运行LyricsX主程序后才会出现`LyricsXHelper`进程
<img width="1355" alt="2017-08-07 16 05 13" src="https://user-images.githubusercontent.com/7870396/29017727-b45f7cd0-7b8a-11e7-8174-f97a624db504.png">

**Comment by ddddxxx** [comment]
是这样的，`LyricsXHelper` 不会与 LyricsX 一同运行，也不会随 iTunes 启动。它唯一的作用是在后台保持运行，并不断检测 iTunes 的状态。如果 iTunes 启动了，它就会启动 LyricsX，然后自己退出。同样的，LyricsX 退出时，会启动 `LyricsXHelper`

请检查 LyricsX 随 iTunes 退出时，LyricsXHelper 的运行状况。

**Comment by koukisakurai** [comment]
`LyricsX` 随 iTunes 退出时，`LyricsXHelper`运行在后台了。重新再开启iTunes，`LyricsXHelper`进程自动关闭，但`LyricsX`依旧没有启动

**Comment by ddddxxx** [comment]
请问 LyricsX.app 是放在应用程序文件夹吗？有些时候沙盒会因此阻止程序启动。

**Comment by koukisakurai** [comment]
是在应用程序文件夹

**Comment by ddddxxx** [comment]
试试这个 [LyricsXHelper.app.zip](https://github.com/ddddxxx/LyricsX/files/1207470/LyricsXHelper.app.zip)

解压后放到 `LyricsX.app/Contents/Library/LoginItems/`，替换原有的文件

**Comment by koukisakurai** [comment]
替换了这个LyricsXHelper后还是原来的情况，`LyricsXHelper`检测到iTunes启动后会自动退出，但依旧没有开启`LyricsX`

**Comment by ddddxxx** [comment]
失败时会有log，请打开`Console.app`，搜索`LyricsXHelper`。然后把信息内容发给我。

**Comment by koukisakurai** [comment]
Failed to read values in CFPrefsPlistSource<0x6180000ee700> (Domain: 3665V726AE.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd

**Comment by koukisakurai** [comment]
应该还是和沙盒有关

**Comment by ddddxxx** [comment]
应该还有一条形如 `launch LyricsX succeed` 或 `launch LyricsX failed [REASON]` 这样的记录

**Comment by koukisakurai** [comment]
默认	14:39:17.296820 +0800	kernel	[LyricsX pid:7522 mux-aware] starting, non-mux-aware app count 0, switch-state 0 IG FBs 0 EG FBs 1:f power-state 0 3D busy HDA idle
故障	14:39:17.340463 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/KCY8NMTG34.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:39:17.340617 +0800	LyricsX	Failed to read values in CFPrefsPlistSource<0x6100000f5480> (Domain: KCY8NMTG34.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
默认	14:39:17.346539 +0800	LyricsX	Faulting in NSHTTPCookieStorage singleton
默认	14:39:17.346564 +0800	LyricsX	Faulting in CFHTTPCookieStorage singleton
默认	14:39:17.346585 +0800	LyricsX	Creating default cookie storage with default identifier
默认	14:39:17.368425 +0800	LyricsX	0x61800006d180 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsObject.db: 4636 bytes
默认	14:39:17.368826 +0800	LyricsX	0x618000077a80 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:39:17.370254 +0800	LyricsX	0x618000077a80 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:39:17.371779 +0800	LyricsX	0x61800007af40 opened /Users/kouki/Library/Keychains/login.keychain-db: 4341348 bytes
默认	14:39:17.377230 +0800	LyricsX	0x61800007d200 opened /Library/Keychains/System.keychain: 113668 bytes
默认	14:39:17.380797 +0800	LyricsX	TIC TCP Conn Start [1:0x610000380ea0]
默认	14:39:17.382272 +0800	LyricsX	TIC TCP Conn Event [1:0x610000380ea0]: 1 Err(0)
默认	14:39:17.382293 +0800	LyricsX	TIC TCP Conn Connected [1:0x610000380ea0]: Err(0)
默认	14:39:17.441776 +0800	LyricsX	TIC Enabling TLS [1:0x610000380ea0]
默认	14:39:17.748281 +0800	LyricsX	TIC TLS Event [1:0x610000380ea0]: 2, Pending(0)
默认	14:39:17.791116 +0800	LyricsX	TIC TLS Event [1:0x610000380ea0]: 11, Pending(0)
默认	14:39:17.791996 +0800	LyricsX	TIC TLS Event [1:0x610000380ea0]: 12, Pending(0)
默认	14:39:17.792039 +0800	LyricsX	TIC TLS Event [1:0x610000380ea0]: 14, Pending(0)
默认	14:39:17.796661 +0800	LyricsX	TIC TLS Trust Result [1:0x610000380ea0]: 0
默认	14:39:17.970466 +0800	LyricsX	TIC TLS Event [1:0x610000380ea0]: 20, Pending(0)
默认	14:39:17.970799 +0800	LyricsX	TIC TCP Conn Event [1:0x610000380ea0]: 8 Err(0)
默认	14:39:17.970821 +0800	LyricsX	TIC TLS Handshake Complete [1:0x610000380ea0]
默认	14:39:28.067810 +0800	kernel	[LyricsX pid 7522 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:10.772
故障	14:39:28.098528 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/3665V726AE.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:39:28.098661 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6080000f9900> (Domain: 3665V726AE.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
故障	14:39:59.322549 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/3665V726AE.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:39:59.322663 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6100000f8800> (Domain: 3665V726AE.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
默认	14:40:05.985970 +0800	kernel	[LyricsX pid:7547 mux-aware] starting, non-mux-aware app count 0, switch-state 0 IG FBs 0 EG FBs 1:f power-state 0 3D busy HDA idle
故障	14:40:06.028742 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/KCY8NMTG34.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:40:06.028893 +0800	LyricsX	Failed to read values in CFPrefsPlistSource<0x6100000e7680> (Domain: KCY8NMTG34.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
默认	14:40:06.034642 +0800	LyricsX	Faulting in NSHTTPCookieStorage singleton
默认	14:40:06.034665 +0800	LyricsX	Faulting in CFHTTPCookieStorage singleton
默认	14:40:06.034682 +0800	LyricsX	Creating default cookie storage with default identifier
默认	14:40:06.056349 +0800	LyricsX	0x60800026fb80 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsObject.db: 4636 bytes
默认	14:40:06.057274 +0800	LyricsX	0x608000272d80 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:40:06.058699 +0800	LyricsX	0x608000272d80 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:40:06.060158 +0800	LyricsX	0x61800026fb00 opened /Users/kouki/Library/Keychains/login.keychain-db: 4341348 bytes
默认	14:40:06.066208 +0800	LyricsX	0x6180002702c0 opened /Library/Keychains/System.keychain: 113668 bytes
默认	14:40:06.069723 +0800	LyricsX	TIC TCP Conn Start [1:0x600000188610]
默认	14:40:06.071106 +0800	LyricsX	TIC TCP Conn Event [1:0x600000188610]: 1 Err(0)
默认	14:40:06.071127 +0800	LyricsX	TIC TCP Conn Connected [1:0x600000188610]: Err(0)
默认	14:40:06.131895 +0800	LyricsX	TIC Enabling TLS [1:0x600000188610]
默认	14:40:06.440378 +0800	LyricsX	TIC TLS Event [1:0x600000188610]: 2, Pending(0)
默认	14:40:06.483399 +0800	LyricsX	TIC TLS Event [1:0x600000188610]: 11, Pending(0)
默认	14:40:06.484303 +0800	LyricsX	TIC TLS Event [1:0x600000188610]: 12, Pending(0)
默认	14:40:06.484339 +0800	LyricsX	TIC TLS Event [1:0x600000188610]: 14, Pending(0)
默认	14:40:06.488868 +0800	LyricsX	TIC TLS Trust Result [1:0x600000188610]: 0
默认	14:40:06.662532 +0800	LyricsX	TIC TLS Event [1:0x600000188610]: 20, Pending(0)
默认	14:40:06.662863 +0800	LyricsX	TIC TCP Conn Event [1:0x600000188610]: 8 Err(0)
默认	14:40:06.662886 +0800	LyricsX	TIC TLS Handshake Complete [1:0x600000188610]
默认	14:40:15.003953 +0800	kernel	[LyricsX pid 7547 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:09.018
故障	14:40:15.033965 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/3665V726AE.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:40:15.034106 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6000000ea100> (Domain: 3665V726AE.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
故障	14:40:27.867686 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/3665V726AE.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:40:27.867831 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6180002e0480> (Domain: 3665V726AE.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
故障	14:40:29.014034 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/3665V726AE.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:40:29.014198 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6080000f8080> (Domain: 3665V726AE.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
故障	14:40:30.348604 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/3665V726AE.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:40:30.348725 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6000000e6d80> (Domain: 3665V726AE.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
默认	14:42:44.561309 +0800	kernel	[LyricsX pid:7635 mux-aware] starting, non-mux-aware app count 0, switch-state 0 IG FBs 0 EG FBs 1:f power-state 0 3D busy HDA idle
故障	14:42:44.609601 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/KCY8NMTG34.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:42:44.609758 +0800	LyricsX	Failed to read values in CFPrefsPlistSource<0x6180000e4f00> (Domain: KCY8NMTG34.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
默认	14:42:44.616966 +0800	LyricsX	Faulting in NSHTTPCookieStorage singleton
默认	14:42:44.616998 +0800	LyricsX	Faulting in CFHTTPCookieStorage singleton
默认	14:42:44.617026 +0800	LyricsX	Creating default cookie storage with default identifier
默认	14:42:44.622570 +0800	LyricsX	0x61800007ab40 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsObject.db: 4636 bytes
默认	14:42:44.623134 +0800	LyricsX	0x608000275340 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:42:44.624758 +0800	LyricsX	0x618000264780 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:42:44.626263 +0800	LyricsX	0x6180002651c0 opened /Users/kouki/Library/Keychains/login.keychain-db: 4341348 bytes
默认	14:42:44.632207 +0800	LyricsX	0x61000007fac0 opened /Library/Keychains/System.keychain: 113668 bytes
默认	14:42:44.637378 +0800	LyricsX	TIC TCP Conn Start [1:0x6100001986d0]
默认	14:42:44.639290 +0800	LyricsX	TIC TCP Conn Event [1:0x6100001986d0]: 1 Err(0)
默认	14:42:44.639324 +0800	LyricsX	TIC TCP Conn Connected [1:0x6100001986d0]: Err(0)
默认	14:42:44.698446 +0800	LyricsX	TIC Enabling TLS [1:0x6100001986d0]
默认	14:42:44.999005 +0800	LyricsX	TIC TLS Event [1:0x6100001986d0]: 2, Pending(0)
默认	14:42:45.042164 +0800	LyricsX	TIC TLS Event [1:0x6100001986d0]: 11, Pending(0)
默认	14:42:45.043292 +0800	LyricsX	TIC TLS Event [1:0x6100001986d0]: 12, Pending(0)
默认	14:42:45.043341 +0800	LyricsX	TIC TLS Event [1:0x6100001986d0]: 14, Pending(0)
默认	14:42:45.050496 +0800	LyricsX	TIC TLS Trust Result [1:0x6100001986d0]: 0
默认	14:42:45.221921 +0800	LyricsX	TIC TLS Event [1:0x6100001986d0]: 20, Pending(0)
默认	14:42:45.222252 +0800	LyricsX	TIC TCP Conn Event [1:0x6100001986d0]: 8 Err(0)
默认	14:42:45.222275 +0800	LyricsX	TIC TLS Handshake Complete [1:0x6100001986d0]
默认	14:42:55.830219 +0800	LyricsX	TIC TCP Conn Event [1:0x6100001986d0]: 2 Err(0)
默认	14:42:55.830350 +0800	LyricsX	TIC TCP Conn Cancel [1:0x6100001986d0]
默认	14:42:55.830485 +0800	LyricsX	TIC TCP Conn Destroyed [1:0x6100001986d0]
默认	14:42:58.204361 +0800	kernel	[LyricsX pid 7635 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:13.643
故障	14:42:58.233888 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/3665V726AE.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:42:58.234018 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6180000ee700> (Domain: 3665V726AE.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
故障	14:46:13.221355 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/3665V726AE.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:46:13.221557 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6100000f0380> (Domain: 3665V726AE.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
默认	14:48:04.278714 +0800	kernel	[LyricsX pid:7783 mux-aware] starting, non-mux-aware app count 0, switch-state 0 IG FBs 0 EG FBs 1:f power-state 0 3D busy HDA idle
故障	14:48:04.322453 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/KCY8NMTG34.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:48:04.322623 +0800	LyricsX	Failed to read values in CFPrefsPlistSource<0x6100000fee00> (Domain: KCY8NMTG34.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
默认	14:48:04.330741 +0800	LyricsX	Faulting in NSHTTPCookieStorage singleton
默认	14:48:04.330776 +0800	LyricsX	Faulting in CFHTTPCookieStorage singleton
默认	14:48:04.330801 +0800	LyricsX	Creating default cookie storage with default identifier
默认	14:48:04.336488 +0800	LyricsX	0x610000078e80 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsObject.db: 4636 bytes
默认	14:48:04.336913 +0800	LyricsX	0x61000007fa40 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:48:04.338782 +0800	LyricsX	0x61000007fa40 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:48:04.340382 +0800	LyricsX	0x608000274580 opened /Users/kouki/Library/Keychains/login.keychain-db: 4341348 bytes
默认	14:48:04.346801 +0800	LyricsX	0x61800007dec0 opened /Library/Keychains/System.keychain: 113668 bytes
默认	14:48:04.351822 +0800	LyricsX	TIC TCP Conn Start [1:0x610000197d10]
默认	14:48:04.354141 +0800	LyricsX	TIC TCP Conn Event [1:0x610000197d10]: 1 Err(0)
默认	14:48:04.354177 +0800	LyricsX	TIC TCP Conn Connected [1:0x610000197d10]: Err(0)
默认	14:48:04.457317 +0800	LyricsX	TIC Enabling TLS [1:0x610000197d10]
默认	14:48:04.795917 +0800	LyricsX	TIC TLS Event [1:0x610000197d10]: 2, Pending(0)
默认	14:48:04.841376 +0800	LyricsX	TIC TLS Event [1:0x610000197d10]: 11, Pending(0)
默认	14:48:04.842263 +0800	LyricsX	TIC TLS Event [1:0x610000197d10]: 12, Pending(0)
默认	14:48:04.842300 +0800	LyricsX	TIC TLS Event [1:0x610000197d10]: 14, Pending(0)
默认	14:48:04.847079 +0800	LyricsX	TIC TLS Trust Result [1:0x610000197d10]: 0
默认	14:48:05.035754 +0800	LyricsX	TIC TLS Event [1:0x610000197d10]: 20, Pending(0)
默认	14:48:05.036044 +0800	LyricsX	TIC TCP Conn Event [1:0x610000197d10]: 8 Err(0)
默认	14:48:05.036073 +0800	LyricsX	TIC TLS Handshake Complete [1:0x610000197d10]
默认	14:48:15.874192 +0800	LyricsX	TIC TCP Conn Event [1:0x610000197d10]: 2 Err(0)
默认	14:48:15.874267 +0800	LyricsX	TIC TCP Conn Cancel [1:0x610000197d10]
默认	14:48:15.874344 +0800	LyricsX	TIC TCP Conn Destroyed [1:0x610000197d10]
默认	14:48:20.662729 +0800	lsd	SecTranslocateCreateSecureDirectoryForURL: created /private/var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/T/AppTranslocation/35E8337D-93E3-43E0-84CC-58FBD5EE8289/d/LyricsXHelper.app
默认	14:48:20.985262 +0800	kernel	[LyricsX pid 7783 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:16.707
故障	14:48:21.047416 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/KCY8NMTG34.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:48:21.047588 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6180000e6b00> (Domain: KCY8NMTG34.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
默认	14:50:33.262280 +0800	kernel	[LyricsX pid:7859 mux-aware] starting, non-mux-aware app count 0, switch-state 0 IG FBs 0 EG FBs 1:f power-state 0 3D busy HDA idle
故障	14:50:33.305410 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/KCY8NMTG34.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:50:33.305574 +0800	LyricsX	Failed to read values in CFPrefsPlistSource<0x6000000ec200> (Domain: KCY8NMTG34.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
默认	14:50:33.311615 +0800	LyricsX	Faulting in NSHTTPCookieStorage singleton
默认	14:50:33.311646 +0800	LyricsX	Faulting in CFHTTPCookieStorage singleton
默认	14:50:33.311675 +0800	LyricsX	Creating default cookie storage with default identifier
默认	14:50:33.332587 +0800	LyricsX	0x60800007bb80 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsObject.db: 4636 bytes
默认	14:50:33.332951 +0800	LyricsX	0x60800007c340 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:50:33.334459 +0800	LyricsX	0x618000071e00 opened /var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/C/ddddxxx.LyricsX//mds/mdsDirectory.db: 50744 bytes
默认	14:50:33.335988 +0800	LyricsX	0x6100002657c0 opened /Users/kouki/Library/Keychains/login.keychain-db: 4341348 bytes
默认	14:50:33.341359 +0800	LyricsX	0x610000267a80 opened /Library/Keychains/System.keychain: 113668 bytes
默认	14:50:33.344950 +0800	LyricsX	TIC TCP Conn Start [1:0x60000018c230]
默认	14:50:33.346296 +0800	LyricsX	TIC TCP Conn Event [1:0x60000018c230]: 1 Err(0)
默认	14:50:33.346327 +0800	LyricsX	TIC TCP Conn Connected [1:0x60000018c230]: Err(0)
默认	14:50:33.409712 +0800	LyricsX	TIC Enabling TLS [1:0x60000018c230]
默认	14:50:33.739194 +0800	LyricsX	TIC TLS Event [1:0x60000018c230]: 2, Pending(0)
默认	14:50:33.784297 +0800	LyricsX	TIC TLS Event [1:0x60000018c230]: 11, Pending(0)
默认	14:50:33.785178 +0800	LyricsX	TIC TLS Event [1:0x60000018c230]: 12, Pending(0)
默认	14:50:33.785238 +0800	LyricsX	TIC TLS Event [1:0x60000018c230]: 14, Pending(0)
默认	14:50:33.789773 +0800	LyricsX	TIC TLS Trust Result [1:0x60000018c230]: 0
默认	14:50:34.146106 +0800	LyricsX	TIC TLS Event [1:0x60000018c230]: 20, Pending(0)
默认	14:50:34.146456 +0800	LyricsX	TIC TCP Conn Event [1:0x60000018c230]: 8 Err(0)
默认	14:50:34.146477 +0800	LyricsX	TIC TLS Handshake Complete [1:0x60000018c230]
默认	14:50:44.715275 +0800	LyricsX	TIC TCP Conn Event [1:0x60000018c230]: 2 Err(0)
默认	14:50:44.715327 +0800	LyricsX	TIC TCP Conn Cancel [1:0x60000018c230]
默认	14:50:44.715376 +0800	LyricsX	TIC TCP Conn Destroyed [1:0x60000018c230]
默认	14:51:02.483188 +0800	lsd	SecTranslocateCreateSecureDirectoryForURL: created /private/var/folders/nh/7mnkp_n10yv7p1yvpyf83tw80000gn/T/AppTranslocation/83C071A9-7BE7-4110-9A0C-74464514E80A/d/LyricsXHelper.app
默认	14:51:04.327231 +0800	kernel	[LyricsX pid 7859 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:31.066
故障	14:51:04.376993 +0800	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/KCY8NMTG34.group.ddddxxx.LyricsX that does not yet exist. Using client-provided container path without resolving symlinks.
错误	14:51:04.377153 +0800	LyricsXHelper	Failed to read values in CFPrefsPlistSource<0x6100000ee180> (Domain: KCY8NMTG34.group.ddddxxx.LyricsX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd

**Comment by koukisakurai** [comment]
没有`launch LyricsX`这样的记录

**Comment by ddddxxx** [comment]
有点奇怪……LyricsXHelper 只有一个出口，经过时必然输出一条log……

我会继续处理这个问题。

**Comment by koukisakurai** [comment]
谢谢

**Comment by ddddxxx** [comment]
请确认 MAS 版本 1.2.1 是否仍有这个问题

**Comment by ddddxxx** [comment]
无人回应，此题关闭。

若仍有问题，请重新启用这一主题。
