### ISSUE TITLE
希望可以添加到 brew cask

### ISSUE THREAD

**Issue by JamesHopbourn** [ddddxxx/LyricsX#82]
希望可以添加到 brew cask 方便下载
谢谢

**Comment by ddddxxx** [comment]
感谢建议。

事实上我正在提交到 Mac App Store。届时我将停止 MAS 以外的下载渠道。你的请求恐怕不能实现。

**Comment by shatteringlass** [comment]
As a non Chinese-speaker, I had to rely on google translate. Do you plan to release the app on MAS and then pull the binaries released on GitHub? I was planning to release the brew formula for easier downloads, it would suck to switch to MAS for this app...

**Comment by ddddxxx** [comment]
@shatteringlass Yes, I'm planning to switch to MAS. I think MAS is friendlier than GitHub for non-technical person.
Could you tell me why you thought MAS sucks?

**Comment by JamesHopbourn** [comment]
OK 了解了 谢谢

**Comment by sfdye** [comment]
+1 for this. Will add lyricsX to my dotfiles.

**Comment by ddddxxx** [comment]
I searched in brew casks and found that @shatteringlass had already added lyricsx. Thank you!

I will continue to release the binaries on GitHub. and update README to reflect this since next release.

**Comment by sfdye** [comment]
@ddddxxx Yes I already installed via cask yesterday. Thanks for the great app.
