### ISSUE TITLE
请求假名注音的Feature

### ISSUE THREAD

**Issue by sequencer** [ddddxxx/LyricsX#83]
先膜dx
---
最近在学日语，听日文歌的时候，感觉对假名注音有一定的需求。
不知道有没有可能做一个[假名注音](https://zh.wikipedia.org/wiki/%E6%8C%AF%E5%81%87%E5%90%8D)的feature了？
参考资料[Teratail](https://teratail.com/questions/40749)

**Comment by ddddxxx** [comment]
// 好像混入了奇怪的东西

我希望以尽可能简洁的方式提供最核心的功能。这个功能实在是太个人化了，我不打算将其加入。
你可以fork一份自己修改，有技术问题可以直接问我。

**Comment by sequencer** [comment]
get了
我fork份自己改改吧
