### ISSUE TITLE
上架Mac App Store？

### ISSUE THREAD

**Issue by oscar-c** [ddddxxx/LyricsX#85]
如题。做的不错，收费也OK。

**Comment by ddddxxx** [comment]
我在三周前就准备好了 1.2.0 版本并尝试提交 Mac App Store，然而不断被 Apple 以版权为由退回。
我仍会继续提交，你可以在源代码中看到欺骗审核人员的尝试。

LyricsX for Mac 永远不会收费（包括 MAS）。如果你认为它对你有帮助并愿意支持开发，你可以在程序中找到支付宝的捐赠链接。

**Comment by wangxufire** [comment]
我怎么感觉还是以前的status bar icon好看点。

**Comment by ddddxxx** [comment]
@wangxufire 以前的 icon 缺乏辨识度。任何一个和音乐相关的应用都可以使用。
