### ISSUE TITLE
无法撤销“Wrong Lyrics”操作

### ISSUE THREAD

**Issue by oscar-c** [ddddxxx/LyricsX#91]
误点之后似乎无法取消？

**Comment by ddddxxx** [comment]
手动搜索歌词并选择，将会撤销此前的错误标记。

**Comment by oscar-c** [comment]
MAS版好像没有手动搜索的功能
![](http://d.pr/i/3JA3xT+)

**Comment by ddddxxx** [comment]
请确保网络通畅（能访问GitHub），然后重新启动程序。

**Comment by oscar-c** [comment]
能访问，重启了，还是这个菜单。

**Comment by ddddxxx** [comment]
非常抱歉，我忘了在 GitHub 上发布新版本。

现已修复，请重启程序。

**Comment by oscar-c** [comment]
可以用了
