### ISSUE TITLE
Search Lyrics窗口打开时点击菜单栏里的“Search Lyrics...“时没反应

### ISSUE THREAD

**Issue by oscar-c** [ddddxxx/LyricsX#94]
希望每次点击菜单里面“Search Lyrics...“时，能聚焦到搜索窗口上，并用当前播放的歌曲信息重新搜索。

**Comment by oscar-c** [comment]
版本：MAS 1.4.2
在搜索歌词窗口打开的时候选择搜索，焦点会回到搜索窗口上，但是Title与Artist不会更新到当前的歌曲的信息。

**Comment by ddddxxx** [comment]
已更新，请等待下一版本发布
