### ISSUE TITLE
在播放Stream的时候，自动暂停LyricsX的功能

### ISSUE THREAD

**Issue by oscar-c** [ddddxxx/LyricsX#95]
iTunes能播放Stream（可以打开一个URL，并添加到Library里面）。这时候LyricsX不应该继续查找歌词。

或者应该按照Stream的歌曲的信息找歌词，而不是按照Stream本身的标题找歌词
![](http://d.pr/i/oO0AId+)
图片中歌曲的信息在框中，而LyricsX搜索的是Stream的名字。

**Comment by ddddxxx** [comment]
我没有使用过这一功能。请问要如何复现？

**Comment by oscar-c** [comment]
关于这个是什么功能，可见 https://support.apple.com/kb/PH19478 中“接入互联网广播”一块。
在哪里可以找到源，可以在这里找： http://dir.xiph.org/by_format/AAC

可以试着在iTunes中添加一个地址 http://dir.xiph.org/listen/753708/listen.m3u ,这是在“第二个网址里面第一个搜到的电台。

不是所有的源都会添加正在播放的歌曲的信息。

**Comment by ddddxxx** [comment]
iTunes 把一个源视为一整个音轨，你所看到的歌曲信息其实是源标题。

我尝试读取源标题，确实成功了。我甚至能按 `Title - Artist` 分离出歌名和歌手。但是进一步的测试使我放弃了所有“互联网广播”相关的功能。

如上所述，一个广播源播放的所有歌曲都是一整轨，不存在任何“歌曲切换”。它的播放进度为“打开广播直到现在所经过的时间”。这使得同步歌词没有任何意义。**广播中不包含歌曲进度信息**。

接下来的版本中，LyricsX 将忽略正在播放的互联网广播。
