### ISSUE TITLE
display a small album artwork on menubar

### ISSUE THREAD

**Issue by Soundsa** [ddddxxx/LyricsX#97]
Hello

I'm really enjoying your app

It's one of my pleasure to look lyrics which is displaying through your app

So, There is one request about your app

How about displaying an small albumart on Menubar instead of your app icon

It would be beautiful to look an albumart with lyrics

just like an tidy music player in our macbook on Menubar

Thank you very much

**Comment by ddddxxx** [comment]
I just implemented this feature, and found the artwork on menubar is too small to recognize.
