### ISSUE TITLE
跟随 iTunes 退出时阻止 iTunes 正常退出

### ISSUE THREAD

**Issue by CourierKyn** [ddddxxx/LyricsX#99]
开启跟随播放器启动和退出，正在播放音乐时退出 iTunes 无法正常退出。这样尝试时，LyricsX 先会退出，而 iTunes 则未能退出，再次退出才能正常退出

**Comment by ddddxxx** [comment]
未能复现，请提供更多信息以便确定问题：

- 系统版本和应用版本？
- iTunes 是未能退出，还是退出之后立刻启动？（观察Dock上的图标是否消失然后出现）

**Comment by CourierKyn** [comment]
macOS Sierra 10.12.6  
LyricsX 1.2.1 (1297)  
不一定要开启跟随播放器启动和退出，只要 LyricsX 已启动，且 iTunes 正在播放音乐，就会出现这种情况。iTunes 是退出之后立刻启动。

**Comment by CourierKyn** [comment]
该问题有时出现

**Comment by ddddxxx** [comment]
请问是否开启了实验室中的自动写入 iTunes 功能？

**Comment by CourierKyn** [comment]
没有

**Comment by ddddxxx** [comment]
我发现了一个可能的错误会导致意外唤醒播放器，但和问题描述稍有差别。
我会先修复这个错误。请等待下一个版本发布。

**Comment by cogitoxin** [comment]
@ddddxxx 相同问题，但是我开启了自动写入iTunes，关闭后恢复正常，希望下一个release能修复。
